// Global solar data - countries, cities, pricing, and solar radiation
// This module replaces the Yemen-only data with worldwide coverage

export interface SolarRadiationData {
  name: string;
  nameEn: string;
  latitude: number;
  longitude: number;
  annualAvg: number; // kWh/m²/day annual average
  monthly: number[]; // Jan-Dec kWh/m²/day
  optimalTiltAngle: number;
  peakSunHours: number;
}

export interface CountryData {
  code: string;
  nameAr: string;
  nameEn: string;
  currency: string;
  currencySymbol: string;
  // Price multiplier relative to US base prices (1.0 = US prices)
  priceMultiplier: number;
  // Specific component price adjustments
  panelPricePerWatt: number; // USD per watt
  lithiumBatteryPricePerKWh: number; // USD per kWh
  leadAcidBatteryPricePerAh12V: number; // USD per Ah for 12V battery
  inverterPricePerWatt: number; // USD per watt
  cablePriceMultiplier: number; // multiplier on base cable prices
  breakerPriceMultiplier: number; // multiplier on base breaker prices
  // Local costs
  installationCostPercent: number; // % of equipment cost
  dieselPricePerLiter: number; // USD
  gridElectricityPrice: number; // USD per kWh
  // Solar data
  cities: SolarRadiationData[];
}

// ============= GLOBAL COUNTRIES DATABASE =============
export const countriesDatabase: CountryData[] = [
  // ===== MIDDLE EAST =====
  {
    code: "YE",
    nameAr: "اليمن",
    nameEn: "Yemen",
    currency: "YER",
    currencySymbol: "﷼",
    priceMultiplier: 1.3,
    panelPricePerWatt: 0.45,
    lithiumBatteryPricePerKWh: 350,
    leadAcidBatteryPricePerAh12V: 3.5,
    inverterPricePerWatt: 0.22,
    cablePriceMultiplier: 1.2,
    breakerPriceMultiplier: 1.3,
    installationCostPercent: 15,
    dieselPricePerLiter: 0.8,
    gridElectricityPrice: 0.05,
    cities: [
      { name: "صنعاء", nameEn: "Sana'a", latitude: 15.35, longitude: 44.21, annualAvg: 5.8, monthly: [5.2, 5.8, 6.5, 6.8, 6.6, 6.4, 5.8, 5.5, 5.9, 5.6, 5.3, 5.0], optimalTiltAngle: 15, peakSunHours: 6.0 },
      { name: "عدن", nameEn: "Aden", latitude: 12.78, longitude: 45.04, annualAvg: 6.2, monthly: [5.8, 6.3, 6.8, 6.9, 6.7, 5.9, 5.4, 5.3, 5.8, 6.1, 6.0, 5.7], optimalTiltAngle: 13, peakSunHours: 6.3 },
      { name: "تعز", nameEn: "Taiz", latitude: 13.58, longitude: 44.02, annualAvg: 6.0, monthly: [5.5, 6.0, 6.6, 6.8, 6.5, 5.8, 5.2, 5.1, 5.6, 5.9, 5.8, 5.4], optimalTiltAngle: 14, peakSunHours: 6.1 },
      { name: "الحديدة", nameEn: "Al Hudaydah", latitude: 14.80, longitude: 42.95, annualAvg: 6.1, monthly: [5.6, 6.1, 6.7, 7.0, 6.8, 6.2, 5.5, 5.2, 5.5, 5.8, 5.7, 5.4], optimalTiltAngle: 15, peakSunHours: 6.2 },
      { name: "حضرموت", nameEn: "Hadhramaut", latitude: 15.94, longitude: 48.38, annualAvg: 6.4, monthly: [6.0, 6.5, 7.0, 7.2, 7.0, 6.8, 6.2, 5.9, 6.3, 6.2, 6.0, 5.8], optimalTiltAngle: 16, peakSunHours: 6.5 },
      { name: "المكلا", nameEn: "Al Mukalla", latitude: 14.53, longitude: 49.13, annualAvg: 6.3, monthly: [5.9, 6.4, 6.9, 7.1, 6.9, 6.5, 5.8, 5.5, 5.9, 6.0, 5.9, 5.7], optimalTiltAngle: 15, peakSunHours: 6.4 },
      { name: "مأرب", nameEn: "Marib", latitude: 15.47, longitude: 45.33, annualAvg: 6.5, monthly: [6.1, 6.6, 7.2, 7.4, 7.2, 7.0, 6.5, 6.2, 6.5, 6.3, 6.1, 5.9], optimalTiltAngle: 16, peakSunHours: 6.6 },
    ],
  },
  {
    code: "SA",
    nameAr: "السعودية",
    nameEn: "Saudi Arabia",
    currency: "SAR",
    currencySymbol: "﷼",
    priceMultiplier: 1.1,
    panelPricePerWatt: 0.35,
    lithiumBatteryPricePerKWh: 300,
    leadAcidBatteryPricePerAh12V: 3.0,
    inverterPricePerWatt: 0.18,
    cablePriceMultiplier: 1.0,
    breakerPriceMultiplier: 1.1,
    installationCostPercent: 12,
    dieselPricePerLiter: 0.15,
    gridElectricityPrice: 0.08,
    cities: [
      { name: "الرياض", nameEn: "Riyadh", latitude: 24.71, longitude: 46.68, annualAvg: 6.5, monthly: [4.8, 5.6, 6.2, 6.8, 7.4, 7.8, 7.5, 7.3, 7.0, 6.0, 5.0, 4.5], optimalTiltAngle: 24, peakSunHours: 6.8 },
      { name: "جدة", nameEn: "Jeddah", latitude: 21.54, longitude: 39.17, annualAvg: 6.3, monthly: [5.0, 5.8, 6.4, 6.9, 7.2, 7.5, 7.0, 6.8, 6.5, 5.8, 5.2, 4.8], optimalTiltAngle: 22, peakSunHours: 6.5 },
      { name: "الدمام", nameEn: "Dammam", latitude: 26.39, longitude: 49.98, annualAvg: 6.0, monthly: [4.5, 5.2, 5.8, 6.5, 7.2, 7.8, 7.5, 7.3, 6.8, 5.5, 4.5, 4.0], optimalTiltAngle: 26, peakSunHours: 6.2 },
      { name: "المدينة المنورة", nameEn: "Madinah", latitude: 24.52, longitude: 39.61, annualAvg: 6.4, monthly: [4.8, 5.5, 6.3, 6.9, 7.5, 7.8, 7.4, 7.1, 6.8, 5.8, 5.0, 4.5], optimalTiltAngle: 25, peakSunHours: 6.6 },
    ],
  },
  {
    code: "AE",
    nameAr: "الإمارات",
    nameEn: "UAE",
    currency: "AED",
    currencySymbol: "د.إ",
    priceMultiplier: 1.0,
    panelPricePerWatt: 0.32,
    lithiumBatteryPricePerKWh: 280,
    leadAcidBatteryPricePerAh12V: 2.8,
    inverterPricePerWatt: 0.17,
    cablePriceMultiplier: 0.9,
    breakerPriceMultiplier: 1.0,
    installationCostPercent: 10,
    dieselPricePerLiter: 0.45,
    gridElectricityPrice: 0.10,
    cities: [
      { name: "أبوظبي", nameEn: "Abu Dhabi", latitude: 24.45, longitude: 54.65, annualAvg: 6.2, monthly: [4.8, 5.5, 6.2, 6.8, 7.3, 7.5, 7.0, 6.8, 6.5, 5.5, 4.8, 4.5], optimalTiltAngle: 24, peakSunHours: 6.4 },
      { name: "دبي", nameEn: "Dubai", latitude: 25.20, longitude: 55.27, annualAvg: 6.1, monthly: [4.7, 5.4, 6.1, 6.7, 7.2, 7.4, 6.9, 6.7, 6.4, 5.4, 4.7, 4.4], optimalTiltAngle: 25, peakSunHours: 6.3 },
      { name: "الشارقة", nameEn: "Sharjah", latitude: 25.35, longitude: 55.42, annualAvg: 6.1, monthly: [4.7, 5.4, 6.1, 6.7, 7.2, 7.4, 6.9, 6.7, 6.4, 5.4, 4.7, 4.4], optimalTiltAngle: 25, peakSunHours: 6.3 },
    ],
  },
  {
    code: "EG",
    nameAr: "مصر",
    nameEn: "Egypt",
    currency: "EGP",
    currencySymbol: "ج.م",
    priceMultiplier: 1.2,
    panelPricePerWatt: 0.38,
    lithiumBatteryPricePerKWh: 320,
    leadAcidBatteryPricePerAh12V: 3.2,
    inverterPricePerWatt: 0.20,
    cablePriceMultiplier: 1.1,
    breakerPriceMultiplier: 1.2,
    installationCostPercent: 13,
    dieselPricePerLiter: 0.30,
    gridElectricityPrice: 0.07,
    cities: [
      { name: "القاهرة", nameEn: "Cairo", latitude: 30.04, longitude: 31.24, annualAvg: 5.8, monthly: [4.0, 4.8, 5.8, 6.5, 7.2, 7.8, 7.5, 7.2, 6.5, 5.2, 4.2, 3.6], optimalTiltAngle: 30, peakSunHours: 6.0 },
      { name: "الأقصر", nameEn: "Luxor", latitude: 25.69, longitude: 32.64, annualAvg: 6.4, monthly: [4.8, 5.6, 6.5, 7.2, 7.8, 8.2, 7.8, 7.5, 7.0, 5.8, 4.8, 4.5], optimalTiltAngle: 26, peakSunHours: 6.6 },
      { name: "أسوان", nameEn: "Aswan", latitude: 24.09, longitude: 32.90, annualAvg: 6.5, monthly: [5.0, 5.8, 6.7, 7.3, 7.9, 8.3, 7.9, 7.6, 7.1, 6.0, 5.0, 4.6], optimalTiltAngle: 24, peakSunHours: 6.7 },
      { name: "الإسكندرية", nameEn: "Alexandria", latitude: 31.20, longitude: 29.92, annualAvg: 5.5, monthly: [3.5, 4.3, 5.3, 6.2, 7.0, 7.6, 7.5, 7.1, 6.2, 4.8, 3.8, 3.2], optimalTiltAngle: 31, peakSunHours: 5.7 },
    ],
  },
  {
    code: "JO",
    nameAr: "الأردن",
    nameEn: "Jordan",
    currency: "JOD",
    currencySymbol: "د.أ",
    priceMultiplier: 1.15,
    panelPricePerWatt: 0.36,
    lithiumBatteryPricePerKWh: 310,
    leadAcidBatteryPricePerAh12V: 3.0,
    inverterPricePerWatt: 0.19,
    cablePriceMultiplier: 1.1,
    breakerPriceMultiplier: 1.15,
    installationCostPercent: 12,
    dieselPricePerLiter: 0.65,
    gridElectricityPrice: 0.12,
    cities: [
      { name: "عمّان", nameEn: "Amman", latitude: 31.95, longitude: 35.93, annualAvg: 5.7, monthly: [3.8, 4.6, 5.6, 6.4, 7.2, 7.8, 7.6, 7.3, 6.5, 5.0, 4.0, 3.5], optimalTiltAngle: 32, peakSunHours: 5.9 },
      { name: "العقبة", nameEn: "Aqaba", latitude: 29.53, longitude: 35.01, annualAvg: 6.2, monthly: [4.5, 5.3, 6.2, 7.0, 7.6, 8.0, 7.8, 7.5, 6.8, 5.5, 4.5, 4.0], optimalTiltAngle: 30, peakSunHours: 6.4 },
    ],
  },
  {
    code: "IQ",
    nameAr: "العراق",
    nameEn: "Iraq",
    currency: "IQD",
    currencySymbol: "ع.د",
    priceMultiplier: 1.25,
    panelPricePerWatt: 0.42,
    lithiumBatteryPricePerKWh: 340,
    leadAcidBatteryPricePerAh12V: 3.3,
    inverterPricePerWatt: 0.21,
    cablePriceMultiplier: 1.15,
    breakerPriceMultiplier: 1.25,
    installationCostPercent: 14,
    dieselPricePerLiter: 0.40,
    gridElectricityPrice: 0.06,
    cities: [
      { name: "بغداد", nameEn: "Baghdad", latitude: 33.31, longitude: 44.37, annualAvg: 5.9, monthly: [3.8, 4.7, 5.7, 6.6, 7.3, 7.9, 7.7, 7.4, 6.6, 5.2, 4.0, 3.5], optimalTiltAngle: 33, peakSunHours: 6.1 },
      { name: "البصرة", nameEn: "Basra", latitude: 30.50, longitude: 47.83, annualAvg: 6.0, monthly: [4.0, 4.9, 5.8, 6.7, 7.4, 8.0, 7.6, 7.3, 6.5, 5.2, 4.2, 3.6], optimalTiltAngle: 31, peakSunHours: 6.2 },
    ],
  },
  {
    code: "OM",
    nameAr: "عُمان",
    nameEn: "Oman",
    currency: "OMR",
    currencySymbol: "ر.ع",
    priceMultiplier: 1.05,
    panelPricePerWatt: 0.34,
    lithiumBatteryPricePerKWh: 290,
    leadAcidBatteryPricePerAh12V: 2.9,
    inverterPricePerWatt: 0.18,
    cablePriceMultiplier: 1.0,
    breakerPriceMultiplier: 1.1,
    installationCostPercent: 11,
    dieselPricePerLiter: 0.25,
    gridElectricityPrice: 0.06,
    cities: [
      { name: "مسقط", nameEn: "Muscat", latitude: 23.59, longitude: 58.39, annualAvg: 6.1, monthly: [4.8, 5.5, 6.2, 6.8, 7.2, 7.0, 6.2, 6.0, 6.2, 5.8, 5.0, 4.6], optimalTiltAngle: 24, peakSunHours: 6.3 },
      { name: "صلالة", nameEn: "Salalah", latitude: 17.02, longitude: 54.09, annualAvg: 6.0, monthly: [5.5, 6.2, 6.8, 7.0, 6.5, 5.2, 4.0, 4.2, 5.0, 5.8, 6.0, 5.5], optimalTiltAngle: 17, peakSunHours: 6.1 },
    ],
  },
  {
    code: "KW",
    nameAr: "الكويت",
    nameEn: "Kuwait",
    currency: "KWD",
    currencySymbol: "د.ك",
    priceMultiplier: 1.1,
    panelPricePerWatt: 0.36,
    lithiumBatteryPricePerKWh: 310,
    leadAcidBatteryPricePerAh12V: 3.0,
    inverterPricePerWatt: 0.19,
    cablePriceMultiplier: 1.05,
    breakerPriceMultiplier: 1.1,
    installationCostPercent: 12,
    dieselPricePerLiter: 0.20,
    gridElectricityPrice: 0.05,
    cities: [
      { name: "الكويت العاصمة", nameEn: "Kuwait City", latitude: 29.38, longitude: 47.97, annualAvg: 6.0, monthly: [4.0, 4.8, 5.6, 6.5, 7.3, 7.8, 7.5, 7.2, 6.5, 5.2, 4.2, 3.6], optimalTiltAngle: 29, peakSunHours: 6.2 },
    ],
  },
  {
    code: "QA",
    nameAr: "قطر",
    nameEn: "Qatar",
    currency: "QAR",
    currencySymbol: "ر.ق",
    priceMultiplier: 1.05,
    panelPricePerWatt: 0.34,
    lithiumBatteryPricePerKWh: 290,
    leadAcidBatteryPricePerAh12V: 2.9,
    inverterPricePerWatt: 0.18,
    cablePriceMultiplier: 1.0,
    breakerPriceMultiplier: 1.05,
    installationCostPercent: 10,
    dieselPricePerLiter: 0.25,
    gridElectricityPrice: 0.06,
    cities: [
      { name: "الدوحة", nameEn: "Doha", latitude: 25.29, longitude: 51.53, annualAvg: 6.1, monthly: [4.6, 5.3, 6.0, 6.6, 7.2, 7.4, 6.9, 6.7, 6.4, 5.5, 4.6, 4.3], optimalTiltAngle: 25, peakSunHours: 6.3 },
    ],
  },
  {
    code: "BH",
    nameAr: "البحرين",
    nameEn: "Bahrain",
    currency: "BHD",
    currencySymbol: "د.ب",
    priceMultiplier: 1.08,
    panelPricePerWatt: 0.35,
    lithiumBatteryPricePerKWh: 300,
    leadAcidBatteryPricePerAh12V: 3.0,
    inverterPricePerWatt: 0.19,
    cablePriceMultiplier: 1.05,
    breakerPriceMultiplier: 1.1,
    installationCostPercent: 11,
    dieselPricePerLiter: 0.22,
    gridElectricityPrice: 0.08,
    cities: [
      { name: "المنامة", nameEn: "Manama", latitude: 26.23, longitude: 50.59, annualAvg: 6.0, monthly: [4.5, 5.2, 5.9, 6.5, 7.1, 7.3, 6.8, 6.6, 6.3, 5.4, 4.5, 4.2], optimalTiltAngle: 26, peakSunHours: 6.2 },
    ],
  },
  {
    code: "LB",
    nameAr: "لبنان",
    nameEn: "Lebanon",
    currency: "LBP",
    currencySymbol: "ل.ل",
    priceMultiplier: 1.4,
    panelPricePerWatt: 0.48,
    lithiumBatteryPricePerKWh: 380,
    leadAcidBatteryPricePerAh12V: 3.8,
    inverterPricePerWatt: 0.24,
    cablePriceMultiplier: 1.3,
    breakerPriceMultiplier: 1.4,
    installationCostPercent: 16,
    dieselPricePerLiter: 1.20,
    gridElectricityPrice: 0.15,
    cities: [
      { name: "بيروت", nameEn: "Beirut", latitude: 33.89, longitude: 35.50, annualAvg: 5.4, monthly: [3.2, 4.0, 5.0, 5.8, 6.8, 7.5, 7.5, 7.2, 6.2, 4.5, 3.2, 2.8], optimalTiltAngle: 34, peakSunHours: 5.6 },
    ],
  },
  {
    code: "PS",
    nameAr: "فلسطين",
    nameEn: "Palestine",
    currency: "ILS",
    currencySymbol: "₪",
    priceMultiplier: 1.35,
    panelPricePerWatt: 0.45,
    lithiumBatteryPricePerKWh: 360,
    leadAcidBatteryPricePerAh12V: 3.5,
    inverterPricePerWatt: 0.23,
    cablePriceMultiplier: 1.25,
    breakerPriceMultiplier: 1.3,
    installationCostPercent: 15,
    dieselPricePerLiter: 1.00,
    gridElectricityPrice: 0.14,
    cities: [
      { name: "القدس", nameEn: "Jerusalem", latitude: 31.77, longitude: 35.23, annualAvg: 5.5, monthly: [3.4, 4.2, 5.2, 6.0, 6.8, 7.5, 7.4, 7.1, 6.2, 4.8, 3.5, 3.0], optimalTiltAngle: 32, peakSunHours: 5.7 },
      { name: "غزة", nameEn: "Gaza", latitude: 31.38, longitude: 34.34, annualAvg: 5.5, monthly: [3.3, 4.1, 5.1, 6.0, 6.7, 7.4, 7.3, 7.0, 6.1, 4.7, 3.4, 3.0], optimalTiltAngle: 31, peakSunHours: 5.7 },
    ],
  },
  // ===== AFRICA =====
  {
    code: "MA",
    nameAr: "المغرب",
    nameEn: "Morocco",
    currency: "MAD",
    currencySymbol: "د.م",
    priceMultiplier: 1.15,
    panelPricePerWatt: 0.38,
    lithiumBatteryPricePerKWh: 320,
    leadAcidBatteryPricePerAh12V: 3.0,
    inverterPricePerWatt: 0.20,
    cablePriceMultiplier: 1.1,
    breakerPriceMultiplier: 1.15,
    installationCostPercent: 13,
    dieselPricePerLiter: 0.90,
    gridElectricityPrice: 0.13,
    cities: [
      { name: "الرباط", nameEn: "Rabat", latitude: 34.02, longitude: -6.84, annualAvg: 5.2, monthly: [3.2, 3.8, 4.8, 5.8, 6.5, 7.0, 7.2, 7.0, 5.8, 4.5, 3.5, 3.0], optimalTiltAngle: 34, peakSunHours: 5.4 },
      { name: "مراكش", nameEn: "Marrakech", latitude: 31.63, longitude: -8.01, annualAvg: 5.8, monthly: [3.8, 4.5, 5.5, 6.3, 6.8, 7.5, 7.6, 7.2, 6.2, 5.0, 4.0, 3.5], optimalTiltAngle: 32, peakSunHours: 6.0 },
      { name: "ورزازات", nameEn: "Ouarzazate", latitude: 30.92, longitude: -6.90, annualAvg: 6.3, monthly: [4.5, 5.2, 6.2, 7.0, 7.5, 8.0, 7.8, 7.5, 6.5, 5.2, 4.5, 4.0], optimalTiltAngle: 31, peakSunHours: 6.5 },
    ],
  },
  {
    code: "DZ",
    nameAr: "الجزائر",
    nameEn: "Algeria",
    currency: "DZD",
    currencySymbol: "د.ج",
    priceMultiplier: 1.2,
    panelPricePerWatt: 0.40,
    lithiumBatteryPricePerKWh: 330,
    leadAcidBatteryPricePerAh12V: 3.2,
    inverterPricePerWatt: 0.21,
    cablePriceMultiplier: 1.15,
    breakerPriceMultiplier: 1.2,
    installationCostPercent: 14,
    dieselPricePerLiter: 0.30,
    gridElectricityPrice: 0.05,
    cities: [
      { name: "الجزائر العاصمة", nameEn: "Algiers", latitude: 36.75, longitude: 3.06, annualAvg: 5.0, monthly: [2.8, 3.5, 4.5, 5.5, 6.2, 7.0, 7.2, 6.8, 5.5, 4.2, 3.0, 2.5], optimalTiltAngle: 37, peakSunHours: 5.2 },
      { name: "ورقلة", nameEn: "Ouargla", latitude: 31.95, longitude: 5.33, annualAvg: 6.2, monthly: [4.2, 5.0, 6.0, 6.8, 7.2, 7.8, 7.6, 7.2, 6.2, 5.0, 4.2, 3.8], optimalTiltAngle: 32, peakSunHours: 6.4 },
    ],
  },
  {
    code: "TN",
    nameAr: "تونس",
    nameEn: "Tunisia",
    currency: "TND",
    currencySymbol: "د.ت",
    priceMultiplier: 1.15,
    panelPricePerWatt: 0.38,
    lithiumBatteryPricePerKWh: 310,
    leadAcidBatteryPricePerAh12V: 3.0,
    inverterPricePerWatt: 0.20,
    cablePriceMultiplier: 1.1,
    breakerPriceMultiplier: 1.15,
    installationCostPercent: 13,
    dieselPricePerLiter: 0.70,
    gridElectricityPrice: 0.10,
    cities: [
      { name: "تونس العاصمة", nameEn: "Tunis", latitude: 36.81, longitude: 10.17, annualAvg: 5.0, monthly: [2.8, 3.5, 4.5, 5.5, 6.2, 7.0, 7.2, 6.8, 5.5, 4.2, 3.0, 2.5], optimalTiltAngle: 37, peakSunHours: 5.2 },
      { name: "صفاقس", nameEn: "Sfax", latitude: 34.74, longitude: 10.76, annualAvg: 5.4, monthly: [3.2, 3.8, 4.8, 5.8, 6.5, 7.2, 7.4, 7.0, 5.8, 4.5, 3.5, 3.0], optimalTiltAngle: 35, peakSunHours: 5.6 },
    ],
  },
  {
    code: "SD",
    nameAr: "السودان",
    nameEn: "Sudan",
    currency: "SDG",
    currencySymbol: "ج.س",
    priceMultiplier: 1.4,
    panelPricePerWatt: 0.48,
    lithiumBatteryPricePerKWh: 380,
    leadAcidBatteryPricePerAh12V: 3.5,
    inverterPricePerWatt: 0.25,
    cablePriceMultiplier: 1.3,
    breakerPriceMultiplier: 1.4,
    installationCostPercent: 16,
    dieselPricePerLiter: 0.60,
    gridElectricityPrice: 0.08,
    cities: [
      { name: "الخرطوم", nameEn: "Khartoum", latitude: 15.50, longitude: 32.56, annualAvg: 6.4, monthly: [5.8, 6.4, 7.0, 7.2, 7.0, 6.8, 6.2, 5.8, 6.2, 6.0, 5.8, 5.6], optimalTiltAngle: 16, peakSunHours: 6.6 },
    ],
  },
  {
    code: "SO",
    nameAr: "الصومال",
    nameEn: "Somalia",
    currency: "SOS",
    currencySymbol: "Sh",
    priceMultiplier: 1.5,
    panelPricePerWatt: 0.50,
    lithiumBatteryPricePerKWh: 400,
    leadAcidBatteryPricePerAh12V: 3.8,
    inverterPricePerWatt: 0.26,
    cablePriceMultiplier: 1.4,
    breakerPriceMultiplier: 1.5,
    installationCostPercent: 18,
    dieselPricePerLiter: 0.90,
    gridElectricityPrice: 0.20,
    cities: [
      { name: "مقديشو", nameEn: "Mogadishu", latitude: 2.05, longitude: 45.34, annualAvg: 5.8, monthly: [5.8, 6.2, 6.5, 5.8, 5.0, 4.5, 4.5, 5.0, 5.5, 5.8, 6.0, 5.8], optimalTiltAngle: 2, peakSunHours: 5.9 },
    ],
  },
  {
    code: "ET",
    nameAr: "إثيوبيا",
    nameEn: "Ethiopia",
    currency: "ETB",
    currencySymbol: "ብር",
    priceMultiplier: 1.35,
    panelPricePerWatt: 0.45,
    lithiumBatteryPricePerKWh: 360,
    leadAcidBatteryPricePerAh12V: 3.4,
    inverterPricePerWatt: 0.23,
    cablePriceMultiplier: 1.25,
    breakerPriceMultiplier: 1.3,
    installationCostPercent: 15,
    dieselPricePerLiter: 0.80,
    gridElectricityPrice: 0.08,
    cities: [
      { name: "أديس أبابا", nameEn: "Addis Ababa", latitude: 9.02, longitude: 38.75, annualAvg: 5.6, monthly: [5.5, 5.8, 6.0, 5.8, 5.5, 5.0, 4.2, 4.5, 5.0, 5.5, 5.8, 5.5], optimalTiltAngle: 9, peakSunHours: 5.8 },
    ],
  },
  {
    code: "NG",
    nameAr: "نيجيريا",
    nameEn: "Nigeria",
    currency: "NGN",
    currencySymbol: "₦",
    priceMultiplier: 1.3,
    panelPricePerWatt: 0.44,
    lithiumBatteryPricePerKWh: 350,
    leadAcidBatteryPricePerAh12V: 3.3,
    inverterPricePerWatt: 0.22,
    cablePriceMultiplier: 1.2,
    breakerPriceMultiplier: 1.3,
    installationCostPercent: 15,
    dieselPricePerLiter: 0.70,
    gridElectricityPrice: 0.12,
    cities: [
      { name: "أبوجا", nameEn: "Abuja", latitude: 9.06, longitude: 7.49, annualAvg: 5.3, monthly: [5.5, 5.8, 5.8, 5.5, 5.0, 4.5, 4.0, 4.0, 4.2, 4.8, 5.5, 5.5], optimalTiltAngle: 9, peakSunHours: 5.5 },
      { name: "لاغوس", nameEn: "Lagos", latitude: 6.52, longitude: 3.38, annualAvg: 4.8, monthly: [5.0, 5.2, 5.2, 4.8, 4.2, 3.8, 3.5, 3.5, 3.8, 4.2, 5.0, 5.0], optimalTiltAngle: 7, peakSunHours: 5.0 },
    ],
  },
  {
    code: "KE",
    nameAr: "كينيا",
    nameEn: "Kenya",
    currency: "KES",
    currencySymbol: "KSh",
    priceMultiplier: 1.25,
    panelPricePerWatt: 0.42,
    lithiumBatteryPricePerKWh: 340,
    leadAcidBatteryPricePerAh12V: 3.2,
    inverterPricePerWatt: 0.22,
    cablePriceMultiplier: 1.2,
    breakerPriceMultiplier: 1.25,
    installationCostPercent: 14,
    dieselPricePerLiter: 0.95,
    gridElectricityPrice: 0.18,
    cities: [
      { name: "نيروبي", nameEn: "Nairobi", latitude: -1.29, longitude: 36.82, annualAvg: 5.5, monthly: [5.8, 6.0, 5.8, 5.2, 4.8, 4.5, 4.2, 4.5, 5.2, 5.5, 5.5, 5.5], optimalTiltAngle: 1, peakSunHours: 5.7 },
    ],
  },
  {
    code: "ZA",
    nameAr: "جنوب أفريقيا",
    nameEn: "South Africa",
    currency: "ZAR",
    currencySymbol: "R",
    priceMultiplier: 1.0,
    panelPricePerWatt: 0.35,
    lithiumBatteryPricePerKWh: 290,
    leadAcidBatteryPricePerAh12V: 2.8,
    inverterPricePerWatt: 0.18,
    cablePriceMultiplier: 0.95,
    breakerPriceMultiplier: 1.0,
    installationCostPercent: 11,
    dieselPricePerLiter: 1.10,
    gridElectricityPrice: 0.15,
    cities: [
      { name: "جوهانسبرغ", nameEn: "Johannesburg", latitude: -26.20, longitude: 28.05, annualAvg: 5.8, monthly: [6.5, 6.0, 5.5, 4.8, 4.5, 4.2, 4.5, 5.2, 5.8, 6.0, 6.2, 6.2], optimalTiltAngle: 26, peakSunHours: 6.0 },
      { name: "كيب تاون", nameEn: "Cape Town", latitude: -33.92, longitude: 18.42, annualAvg: 5.7, monthly: [7.0, 6.5, 5.5, 4.2, 3.2, 2.8, 3.0, 3.8, 5.0, 5.8, 6.5, 6.8], optimalTiltAngle: 34, peakSunHours: 5.9 },
    ],
  },
  // ===== ASIA =====
  {
    code: "IN",
    nameAr: "الهند",
    nameEn: "India",
    currency: "INR",
    currencySymbol: "₹",
    priceMultiplier: 0.8,
    panelPricePerWatt: 0.28,
    lithiumBatteryPricePerKWh: 250,
    leadAcidBatteryPricePerAh12V: 2.2,
    inverterPricePerWatt: 0.14,
    cablePriceMultiplier: 0.85,
    breakerPriceMultiplier: 0.9,
    installationCostPercent: 8,
    dieselPricePerLiter: 0.90,
    gridElectricityPrice: 0.10,
    cities: [
      { name: "نيودلهي", nameEn: "New Delhi", latitude: 28.61, longitude: 77.21, annualAvg: 5.5, monthly: [4.2, 5.0, 6.0, 6.5, 6.5, 5.8, 5.0, 5.0, 5.2, 5.0, 4.5, 4.0], optimalTiltAngle: 29, peakSunHours: 5.7 },
      { name: "مومباي", nameEn: "Mumbai", latitude: 19.08, longitude: 72.88, annualAvg: 5.4, monthly: [5.2, 5.5, 6.0, 6.2, 5.8, 4.2, 3.5, 3.5, 4.0, 4.8, 5.5, 5.2], optimalTiltAngle: 19, peakSunHours: 5.6 },
      { name: "بنغالور", nameEn: "Bangalore", latitude: 12.97, longitude: 77.59, annualAvg: 5.5, monthly: [5.2, 5.8, 6.2, 5.8, 5.2, 4.5, 4.2, 4.5, 4.8, 4.8, 5.0, 5.0], optimalTiltAngle: 13, peakSunHours: 5.7 },
    ],
  },
  {
    code: "PK",
    nameAr: "باكستان",
    nameEn: "Pakistan",
    currency: "PKR",
    currencySymbol: "₨",
    priceMultiplier: 0.9,
    panelPricePerWatt: 0.30,
    lithiumBatteryPricePerKWh: 260,
    leadAcidBatteryPricePerAh12V: 2.5,
    inverterPricePerWatt: 0.15,
    cablePriceMultiplier: 0.9,
    breakerPriceMultiplier: 0.95,
    installationCostPercent: 10,
    dieselPricePerLiter: 0.85,
    gridElectricityPrice: 0.12,
    cities: [
      { name: "إسلام آباد", nameEn: "Islamabad", latitude: 33.69, longitude: 73.04, annualAvg: 5.4, monthly: [4.0, 4.8, 5.5, 6.2, 6.5, 6.2, 5.2, 5.0, 5.2, 5.0, 4.5, 3.8], optimalTiltAngle: 34, peakSunHours: 5.6 },
      { name: "كراتشي", nameEn: "Karachi", latitude: 24.86, longitude: 67.01, annualAvg: 5.8, monthly: [5.0, 5.5, 6.2, 6.5, 6.5, 5.8, 5.0, 4.8, 5.2, 5.5, 5.2, 4.8], optimalTiltAngle: 25, peakSunHours: 6.0 },
    ],
  },
  {
    code: "BD",
    nameAr: "بنغلاديش",
    nameEn: "Bangladesh",
    currency: "BDT",
    currencySymbol: "৳",
    priceMultiplier: 0.85,
    panelPricePerWatt: 0.30,
    lithiumBatteryPricePerKWh: 260,
    leadAcidBatteryPricePerAh12V: 2.4,
    inverterPricePerWatt: 0.16,
    cablePriceMultiplier: 0.9,
    breakerPriceMultiplier: 0.95,
    installationCostPercent: 10,
    dieselPricePerLiter: 0.75,
    gridElectricityPrice: 0.08,
    cities: [
      { name: "دكا", nameEn: "Dhaka", latitude: 23.81, longitude: 90.41, annualAvg: 4.8, monthly: [4.5, 5.0, 5.5, 5.8, 5.2, 4.2, 3.8, 3.8, 4.0, 4.5, 4.8, 4.5], optimalTiltAngle: 24, peakSunHours: 5.0 },
    ],
  },
  {
    code: "TH",
    nameAr: "تايلاند",
    nameEn: "Thailand",
    currency: "THB",
    currencySymbol: "฿",
    priceMultiplier: 0.9,
    panelPricePerWatt: 0.32,
    lithiumBatteryPricePerKWh: 270,
    leadAcidBatteryPricePerAh12V: 2.5,
    inverterPricePerWatt: 0.16,
    cablePriceMultiplier: 0.9,
    breakerPriceMultiplier: 0.95,
    installationCostPercent: 10,
    dieselPricePerLiter: 0.80,
    gridElectricityPrice: 0.11,
    cities: [
      { name: "بانكوك", nameEn: "Bangkok", latitude: 13.76, longitude: 100.50, annualAvg: 5.0, monthly: [4.8, 5.2, 5.5, 5.2, 4.5, 4.2, 4.0, 4.0, 4.2, 4.5, 4.8, 4.8], optimalTiltAngle: 14, peakSunHours: 5.2 },
    ],
  },
  {
    code: "MY",
    nameAr: "ماليزيا",
    nameEn: "Malaysia",
    currency: "MYR",
    currencySymbol: "RM",
    priceMultiplier: 0.95,
    panelPricePerWatt: 0.33,
    lithiumBatteryPricePerKWh: 280,
    leadAcidBatteryPricePerAh12V: 2.6,
    inverterPricePerWatt: 0.17,
    cablePriceMultiplier: 0.95,
    breakerPriceMultiplier: 1.0,
    installationCostPercent: 10,
    dieselPricePerLiter: 0.55,
    gridElectricityPrice: 0.10,
    cities: [
      { name: "كوالالمبور", nameEn: "Kuala Lumpur", latitude: 3.14, longitude: 101.69, annualAvg: 4.8, monthly: [4.5, 5.0, 5.0, 4.8, 4.5, 4.2, 4.2, 4.2, 4.5, 4.5, 4.2, 4.2], optimalTiltAngle: 3, peakSunHours: 5.0 },
    ],
  },
  {
    code: "ID",
    nameAr: "إندونيسيا",
    nameEn: "Indonesia",
    currency: "IDR",
    currencySymbol: "Rp",
    priceMultiplier: 0.9,
    panelPricePerWatt: 0.32,
    lithiumBatteryPricePerKWh: 270,
    leadAcidBatteryPricePerAh12V: 2.5,
    inverterPricePerWatt: 0.16,
    cablePriceMultiplier: 0.9,
    breakerPriceMultiplier: 0.95,
    installationCostPercent: 10,
    dieselPricePerLiter: 0.70,
    gridElectricityPrice: 0.10,
    cities: [
      { name: "جاكرتا", nameEn: "Jakarta", latitude: -6.21, longitude: 106.85, annualAvg: 4.5, monthly: [4.2, 4.5, 4.5, 4.2, 3.8, 3.8, 4.0, 4.2, 4.5, 4.5, 4.5, 4.2], optimalTiltAngle: 6, peakSunHours: 4.7 },
    ],
  },
  {
    code: "PH",
    nameAr: "الفلبين",
    nameEn: "Philippines",
    currency: "PHP",
    currencySymbol: "₱",
    priceMultiplier: 1.0,
    panelPricePerWatt: 0.35,
    lithiumBatteryPricePerKWh: 300,
    leadAcidBatteryPricePerAh12V: 2.8,
    inverterPricePerWatt: 0.18,
    cablePriceMultiplier: 1.0,
    breakerPriceMultiplier: 1.05,
    installationCostPercent: 12,
    dieselPricePerLiter: 0.85,
    gridElectricityPrice: 0.18,
    cities: [
      { name: "مانيلا", nameEn: "Manila", latitude: 14.60, longitude: 120.98, annualAvg: 5.0, monthly: [4.5, 5.0, 5.5, 5.8, 5.0, 4.2, 3.8, 3.8, 4.2, 4.5, 4.5, 4.2], optimalTiltAngle: 15, peakSunHours: 5.2 },
    ],
  },
  // ===== EUROPE =====
  {
    code: "DE",
    nameAr: "ألمانيا",
    nameEn: "Germany",
    currency: "EUR",
    currencySymbol: "€",
    priceMultiplier: 1.3,
    panelPricePerWatt: 0.40,
    lithiumBatteryPricePerKWh: 350,
    leadAcidBatteryPricePerAh12V: 3.2,
    inverterPricePerWatt: 0.20,
    cablePriceMultiplier: 1.2,
    breakerPriceMultiplier: 1.3,
    installationCostPercent: 18,
    dieselPricePerLiter: 1.50,
    gridElectricityPrice: 0.30,
    cities: [
      { name: "برلين", nameEn: "Berlin", latitude: 52.52, longitude: 13.41, annualAvg: 3.2, monthly: [1.0, 1.8, 3.0, 4.2, 5.0, 5.2, 5.0, 4.5, 3.2, 2.0, 1.0, 0.8], optimalTiltAngle: 35, peakSunHours: 3.4 },
      { name: "ميونخ", nameEn: "Munich", latitude: 48.14, longitude: 11.58, annualAvg: 3.4, monthly: [1.2, 2.0, 3.2, 4.2, 5.0, 5.5, 5.2, 4.8, 3.5, 2.2, 1.2, 0.8], optimalTiltAngle: 35, peakSunHours: 3.6 },
    ],
  },
  {
    code: "ES",
    nameAr: "إسبانيا",
    nameEn: "Spain",
    currency: "EUR",
    currencySymbol: "€",
    priceMultiplier: 1.1,
    panelPricePerWatt: 0.36,
    lithiumBatteryPricePerKWh: 310,
    leadAcidBatteryPricePerAh12V: 3.0,
    inverterPricePerWatt: 0.18,
    cablePriceMultiplier: 1.05,
    breakerPriceMultiplier: 1.1,
    installationCostPercent: 14,
    dieselPricePerLiter: 1.30,
    gridElectricityPrice: 0.22,
    cities: [
      { name: "مدريد", nameEn: "Madrid", latitude: 40.42, longitude: -3.70, annualAvg: 5.0, monthly: [2.5, 3.5, 4.8, 5.5, 6.2, 6.8, 7.0, 6.5, 5.2, 3.8, 2.8, 2.2], optimalTiltAngle: 40, peakSunHours: 5.2 },
      { name: "إشبيلية", nameEn: "Seville", latitude: 37.39, longitude: -5.98, annualAvg: 5.4, monthly: [2.8, 3.5, 5.0, 5.8, 6.5, 7.2, 7.5, 7.0, 5.5, 4.0, 3.0, 2.5], optimalTiltAngle: 37, peakSunHours: 5.6 },
    ],
  },
  {
    code: "GB",
    nameAr: "المملكة المتحدة",
    nameEn: "United Kingdom",
    currency: "GBP",
    currencySymbol: "£",
    priceMultiplier: 1.4,
    panelPricePerWatt: 0.45,
    lithiumBatteryPricePerKWh: 380,
    leadAcidBatteryPricePerAh12V: 3.5,
    inverterPricePerWatt: 0.22,
    cablePriceMultiplier: 1.3,
    breakerPriceMultiplier: 1.4,
    installationCostPercent: 20,
    dieselPricePerLiter: 1.50,
    gridElectricityPrice: 0.28,
    cities: [
      { name: "لندن", nameEn: "London", latitude: 51.51, longitude: -0.13, annualAvg: 2.8, monthly: [0.8, 1.5, 2.5, 3.8, 4.5, 4.8, 4.5, 4.0, 3.0, 1.8, 1.0, 0.6], optimalTiltAngle: 35, peakSunHours: 3.0 },
    ],
  },
  {
    code: "FR",
    nameAr: "فرنسا",
    nameEn: "France",
    currency: "EUR",
    currencySymbol: "€",
    priceMultiplier: 1.25,
    panelPricePerWatt: 0.40,
    lithiumBatteryPricePerKWh: 340,
    leadAcidBatteryPricePerAh12V: 3.2,
    inverterPricePerWatt: 0.20,
    cablePriceMultiplier: 1.15,
    breakerPriceMultiplier: 1.2,
    installationCostPercent: 16,
    dieselPricePerLiter: 1.45,
    gridElectricityPrice: 0.20,
    cities: [
      { name: "باريس", nameEn: "Paris", latitude: 48.86, longitude: 2.35, annualAvg: 3.2, monthly: [1.0, 1.8, 3.0, 4.0, 4.8, 5.2, 5.0, 4.5, 3.5, 2.2, 1.2, 0.8], optimalTiltAngle: 35, peakSunHours: 3.4 },
      { name: "مارسيليا", nameEn: "Marseille", latitude: 43.30, longitude: 5.37, annualAvg: 4.5, monthly: [2.0, 3.0, 4.2, 5.2, 5.8, 6.5, 6.5, 6.0, 4.8, 3.2, 2.2, 1.8], optimalTiltAngle: 38, peakSunHours: 4.7 },
    ],
  },
  {
    code: "IT",
    nameAr: "إيطاليا",
    nameEn: "Italy",
    currency: "EUR",
    currencySymbol: "€",
    priceMultiplier: 1.2,
    panelPricePerWatt: 0.38,
    lithiumBatteryPricePerKWh: 330,
    leadAcidBatteryPricePerAh12V: 3.1,
    inverterPricePerWatt: 0.19,
    cablePriceMultiplier: 1.1,
    breakerPriceMultiplier: 1.15,
    installationCostPercent: 15,
    dieselPricePerLiter: 1.45,
    gridElectricityPrice: 0.23,
    cities: [
      { name: "روما", nameEn: "Rome", latitude: 41.90, longitude: 12.50, annualAvg: 4.5, monthly: [2.2, 3.0, 4.2, 5.0, 5.8, 6.5, 6.5, 6.0, 4.8, 3.2, 2.2, 1.8], optimalTiltAngle: 35, peakSunHours: 4.7 },
      { name: "باليرمو", nameEn: "Palermo", latitude: 38.13, longitude: 13.36, annualAvg: 5.0, monthly: [2.5, 3.2, 4.5, 5.5, 6.2, 7.0, 7.2, 6.5, 5.2, 3.8, 2.8, 2.2], optimalTiltAngle: 38, peakSunHours: 5.2 },
    ],
  },
  {
    code: "TR",
    nameAr: "تركيا",
    nameEn: "Turkey",
    currency: "TRY",
    currencySymbol: "₺",
    priceMultiplier: 1.15,
    panelPricePerWatt: 0.38,
    lithiumBatteryPricePerKWh: 320,
    leadAcidBatteryPricePerAh12V: 3.0,
    inverterPricePerWatt: 0.19,
    cablePriceMultiplier: 1.1,
    breakerPriceMultiplier: 1.15,
    installationCostPercent: 13,
    dieselPricePerLiter: 1.10,
    gridElectricityPrice: 0.12,
    cities: [
      { name: "إسطنبول", nameEn: "Istanbul", latitude: 41.01, longitude: 28.98, annualAvg: 4.0, monthly: [1.8, 2.5, 3.5, 4.5, 5.2, 5.8, 5.8, 5.5, 4.2, 3.0, 2.0, 1.5], optimalTiltAngle: 38, peakSunHours: 4.2 },
      { name: "أنقرة", nameEn: "Ankara", latitude: 39.93, longitude: 32.86, annualAvg: 4.5, monthly: [2.2, 3.0, 4.0, 5.0, 5.5, 6.2, 6.2, 5.8, 4.8, 3.5, 2.5, 2.0], optimalTiltAngle: 36, peakSunHours: 4.7 },
    ],
  },
  // ===== AMERICAS =====
  {
    code: "US",
    nameAr: "الولايات المتحدة",
    nameEn: "United States",
    currency: "USD",
    currencySymbol: "$",
    priceMultiplier: 1.0,
    panelPricePerWatt: 0.35,
    lithiumBatteryPricePerKWh: 300,
    leadAcidBatteryPricePerAh12V: 2.8,
    inverterPricePerWatt: 0.18,
    cablePriceMultiplier: 1.0,
    breakerPriceMultiplier: 1.0,
    installationCostPercent: 15,
    dieselPricePerLiter: 1.00,
    gridElectricityPrice: 0.14,
    cities: [
      { name: "لوس أنجلوس", nameEn: "Los Angeles", latitude: 34.05, longitude: -118.24, annualAvg: 5.5, monthly: [3.5, 4.2, 5.5, 6.2, 6.5, 6.8, 7.0, 6.5, 5.5, 4.5, 3.5, 3.2], optimalTiltAngle: 34, peakSunHours: 5.7 },
      { name: "فينيكس", nameEn: "Phoenix", latitude: 33.45, longitude: -112.07, annualAvg: 6.5, monthly: [4.5, 5.5, 6.5, 7.5, 7.8, 7.5, 6.8, 6.5, 6.0, 5.5, 4.5, 4.0], optimalTiltAngle: 33, peakSunHours: 6.7 },
      { name: "نيويورك", nameEn: "New York", latitude: 40.71, longitude: -74.01, annualAvg: 4.2, monthly: [2.2, 3.0, 4.0, 4.8, 5.2, 5.5, 5.5, 5.0, 4.2, 3.0, 2.2, 1.8], optimalTiltAngle: 38, peakSunHours: 4.4 },
      { name: "هيوستن", nameEn: "Houston", latitude: 29.76, longitude: -95.37, annualAvg: 4.8, monthly: [3.2, 3.8, 4.5, 5.0, 5.2, 5.5, 5.5, 5.2, 4.8, 4.2, 3.5, 3.0], optimalTiltAngle: 30, peakSunHours: 5.0 },
    ],
  },
  {
    code: "BR",
    nameAr: "البرازيل",
    nameEn: "Brazil",
    currency: "BRL",
    currencySymbol: "R$",
    priceMultiplier: 1.1,
    panelPricePerWatt: 0.36,
    lithiumBatteryPricePerKWh: 310,
    leadAcidBatteryPricePerAh12V: 2.9,
    inverterPricePerWatt: 0.18,
    cablePriceMultiplier: 1.05,
    breakerPriceMultiplier: 1.1,
    installationCostPercent: 14,
    dieselPricePerLiter: 0.90,
    gridElectricityPrice: 0.15,
    cities: [
      { name: "ساو باولو", nameEn: "São Paulo", latitude: -23.55, longitude: -46.63, annualAvg: 4.8, monthly: [5.0, 5.2, 4.8, 4.2, 3.8, 3.5, 3.8, 4.5, 4.2, 4.5, 5.0, 5.0], optimalTiltAngle: 24, peakSunHours: 5.0 },
      { name: "ريو دي جانيرو", nameEn: "Rio de Janeiro", latitude: -22.91, longitude: -43.17, annualAvg: 4.8, monthly: [5.2, 5.5, 5.0, 4.2, 3.8, 3.5, 3.5, 4.2, 4.0, 4.5, 5.0, 5.0], optimalTiltAngle: 23, peakSunHours: 5.0 },
    ],
  },
  {
    code: "MX",
    nameAr: "المكسيك",
    nameEn: "Mexico",
    currency: "MXN",
    currencySymbol: "$",
    priceMultiplier: 1.0,
    panelPricePerWatt: 0.35,
    lithiumBatteryPricePerKWh: 300,
    leadAcidBatteryPricePerAh12V: 2.8,
    inverterPricePerWatt: 0.18,
    cablePriceMultiplier: 1.0,
    breakerPriceMultiplier: 1.05,
    installationCostPercent: 12,
    dieselPricePerLiter: 0.90,
    gridElectricityPrice: 0.12,
    cities: [
      { name: "مكسيكو سيتي", nameEn: "Mexico City", latitude: 19.43, longitude: -99.13, annualAvg: 5.5, monthly: [5.0, 5.5, 6.0, 5.8, 5.2, 4.8, 5.0, 5.0, 4.5, 4.8, 5.0, 5.0], optimalTiltAngle: 19, peakSunHours: 5.7 },
    ],
  },
  // ===== OCEANIA =====
  {
    code: "AU",
    nameAr: "أستراليا",
    nameEn: "Australia",
    currency: "AUD",
    currencySymbol: "A$",
    priceMultiplier: 1.1,
    panelPricePerWatt: 0.38,
    lithiumBatteryPricePerKWh: 320,
    leadAcidBatteryPricePerAh12V: 3.0,
    inverterPricePerWatt: 0.19,
    cablePriceMultiplier: 1.1,
    breakerPriceMultiplier: 1.1,
    installationCostPercent: 13,
    dieselPricePerLiter: 1.30,
    gridElectricityPrice: 0.25,
    cities: [
      { name: "سيدني", nameEn: "Sydney", latitude: -33.87, longitude: 151.21, annualAvg: 5.0, monthly: [5.8, 5.2, 4.5, 3.8, 3.2, 2.8, 3.0, 3.8, 4.8, 5.2, 5.5, 5.8], optimalTiltAngle: 34, peakSunHours: 5.2 },
      { name: "برث", nameEn: "Perth", latitude: -31.95, longitude: 115.86, annualAvg: 5.8, monthly: [6.8, 6.5, 5.5, 4.2, 3.2, 2.8, 3.0, 3.5, 4.8, 5.5, 6.2, 6.5], optimalTiltAngle: 32, peakSunHours: 6.0 },
      { name: "بريزبان", nameEn: "Brisbane", latitude: -27.47, longitude: 153.03, annualAvg: 5.2, monthly: [5.5, 5.0, 4.8, 4.2, 3.8, 3.5, 3.8, 4.5, 5.2, 5.5, 5.8, 5.8], optimalTiltAngle: 27, peakSunHours: 5.4 },
    ],
  },
  // ===== CENTRAL ASIA =====
  {
    code: "UZ",
    nameAr: "أوزبكستان",
    nameEn: "Uzbekistan",
    currency: "UZS",
    currencySymbol: "сўм",
    priceMultiplier: 1.1,
    panelPricePerWatt: 0.36,
    lithiumBatteryPricePerKWh: 300,
    leadAcidBatteryPricePerAh12V: 2.8,
    inverterPricePerWatt: 0.18,
    cablePriceMultiplier: 1.0,
    breakerPriceMultiplier: 1.1,
    installationCostPercent: 12,
    dieselPricePerLiter: 0.65,
    gridElectricityPrice: 0.06,
    cities: [
      { name: "طشقند", nameEn: "Tashkent", latitude: 41.30, longitude: 69.28, annualAvg: 5.0, monthly: [2.5, 3.2, 4.2, 5.2, 6.0, 6.8, 6.5, 6.0, 5.0, 3.8, 2.8, 2.2], optimalTiltAngle: 38, peakSunHours: 5.2 },
    ],
  },
];

// ============= HELPER FUNCTIONS =============

/** Get all countries sorted by Arabic name */
export function getAllCountries(): CountryData[] {
  return [...countriesDatabase].sort((a, b) => a.nameAr.localeCompare(b.nameAr, 'ar'));
}

/** Get country by code */
export function getCountryByCode(code: string): CountryData | undefined {
  return countriesDatabase.find(c => c.code === code);
}

/** Calculate solar radiation for a given latitude using a simplified model */
export function estimateSolarRadiation(latitude: number): {
  annualAvg: number;
  monthly: number[];
  optimalTiltAngle: number;
  peakSunHours: number;
} {
  const absLat = Math.abs(latitude);

  // Base annual average decreases with latitude
  let baseAnnual: number;
  if (absLat <= 15) baseAnnual = 5.8;
  else if (absLat <= 25) baseAnnual = 5.8 - (absLat - 15) * 0.03;
  else if (absLat <= 35) baseAnnual = 5.5 - (absLat - 25) * 0.05;
  else if (absLat <= 45) baseAnnual = 5.0 - (absLat - 35) * 0.08;
  else baseAnnual = 4.2 - (absLat - 45) * 0.06;

  // Monthly variation (more extreme at higher latitudes)
  const variation = absLat <= 20 ? 0.8 : absLat <= 35 ? 1.2 : 1.8;
  const isNorth = latitude >= 0;
  const monthly = Array.from({ length: 12 }, (_, i) => {
    const month = i; // 0=Jan, 11=Dec
    // Summer peaks around June (month 5) in Northern hemisphere
    const seasonAngle = isNorth
      ? Math.cos(((month - 6) / 12) * 2 * Math.PI)
      : Math.cos(((month - 0) / 12) * 2 * Math.PI);
    return Math.max(1.0, baseAnnual + seasonAngle * variation);
  });

  const optimalTiltAngle = Math.round(absLat * 0.9);
  const peakSunHours = Math.round(baseAnnual * 100) / 100;

  return {
    annualAvg: Math.round(baseAnnual * 10) / 10,
    monthly: monthly.map(v => Math.round(v * 10) / 10),
    optimalTiltAngle,
    peakSunHours,
  };
}

/** Calculate country-specific component prices */
export function getLocalizedPrices(country: CountryData) {
  return {
    panelPricePerWatt: country.panelPricePerWatt,
    lithiumBatteryPricePerKWh: country.lithiumBatteryPricePerKWh,
    leadAcidBatteryPricePerAh12V: country.leadAcidBatteryPricePerAh12V,
    inverterPricePerWatt: country.inverterPricePerWatt,
    cablePriceMultiplier: country.cablePriceMultiplier,
    breakerPriceMultiplier: country.breakerPriceMultiplier,
    installationCostPercent: country.installationCostPercent,
    dieselPricePerLiter: country.dieselPricePerLiter,
    gridElectricityPrice: country.gridElectricityPrice,
    currency: country.currency,
    currencySymbol: country.currencySymbol,
  };
}

// Keep backward compatibility with yemenGovernorates
export const yemenGovernorates: SolarRadiationData[] = countriesDatabase.find(c => c.code === 'YE')?.cities || [];

// Re-export cable and breaker specs (unchanged - universal)
export interface CableSpec {
  crossSection: number;
  maxCurrentAC: number;
  maxCurrentDC: number;
  resistancePerKm: number;
  voltageDropPerAmpPerKm: number;
  pricePerMeter: number;
}

export const cableSpecs: CableSpec[] = [
  { crossSection: 1.5, maxCurrentAC: 14, maxCurrentDC: 12, resistancePerKm: 12.1, voltageDropPerAmpPerKm: 0.025, pricePerMeter: 0.3 },
  { crossSection: 2.5, maxCurrentAC: 19, maxCurrentDC: 16, resistancePerKm: 7.41, voltageDropPerAmpPerKm: 0.016, pricePerMeter: 0.5 },
  { crossSection: 4, maxCurrentAC: 26, maxCurrentDC: 22, resistancePerKm: 4.61, voltageDropPerAmpPerKm: 0.010, pricePerMeter: 0.7 },
  { crossSection: 6, maxCurrentAC: 34, maxCurrentDC: 29, resistancePerKm: 3.08, voltageDropPerAmpPerKm: 0.0064, pricePerMeter: 1.0 },
  { crossSection: 10, maxCurrentAC: 48, maxCurrentDC: 40, resistancePerKm: 1.83, voltageDropPerAmpPerKm: 0.0038, pricePerMeter: 1.5 },
  { crossSection: 16, maxCurrentAC: 65, maxCurrentDC: 54, resistancePerKm: 1.15, voltageDropPerAmpPerKm: 0.0024, pricePerMeter: 2.2 },
  { crossSection: 25, maxCurrentAC: 85, maxCurrentDC: 71, resistancePerKm: 0.727, voltageDropPerAmpPerKm: 0.0015, pricePerMeter: 3.5 },
  { crossSection: 35, maxCurrentAC: 105, maxCurrentDC: 88, resistancePerKm: 0.524, voltageDropPerAmpPerKm: 0.0011, pricePerMeter: 4.5 },
  { crossSection: 50, maxCurrentAC: 130, maxCurrentDC: 110, resistancePerKm: 0.387, voltageDropPerAmpPerKm: 0.00081, pricePerMeter: 6.0 },
  { crossSection: 70, maxCurrentAC: 170, maxCurrentDC: 140, resistancePerKm: 0.268, voltageDropPerAmpPerKm: 0.00056, pricePerMeter: 8.5 },
  { crossSection: 95, maxCurrentAC: 210, maxCurrentDC: 175, resistancePerKm: 0.193, voltageDropPerAmpPerKm: 0.00040, pricePerMeter: 12.0 },
  { crossSection: 120, maxCurrentAC: 245, maxCurrentDC: 200, resistancePerKm: 0.153, voltageDropPerAmpPerKm: 0.00032, pricePerMeter: 15.0 },
];

export interface BreakerSpec {
  rating: number;
  typicalApplication: string;
  typicalApplicationAr: string;
  price: number;
}

export const breakerSpecs: BreakerSpec[] = [
  { rating: 6, typicalApplication: "Lighting circuits", typicalApplicationAr: "دوائر الإضاءة", price: 3 },
  { rating: 10, typicalApplication: "Small loads", typicalApplicationAr: "أحمال صغيرة", price: 3 },
  { rating: 16, typicalApplication: "General outlets", typicalApplicationAr: "مقابس عامة", price: 4 },
  { rating: 20, typicalApplication: "Medium loads", typicalApplicationAr: "أحمال متوسطة", price: 5 },
  { rating: 25, typicalApplication: "AC units small", typicalApplicationAr: "تكييفات صغيرة", price: 6 },
  { rating: 32, typicalApplication: "AC units medium", typicalApplicationAr: "تكييفات متوسطة", price: 7 },
  { rating: 40, typicalApplication: "Sub-panels", typicalApplicationAr: "لوحات فرعية", price: 10 },
  { rating: 50, typicalApplication: "Large loads", typicalApplicationAr: "أحمال كبيرة", price: 12 },
  { rating: 63, typicalApplication: "Main breaker small", typicalApplicationAr: "قاطع رئيسي صغير", price: 15 },
  { rating: 80, typicalApplication: "Main breaker medium", typicalApplicationAr: "قاطع رئيسي متوسط", price: 20 },
  { rating: 100, typicalApplication: "Main breaker", typicalApplicationAr: "قاطع رئيسي", price: 25 },
  { rating: 125, typicalApplication: "Main breaker large", typicalApplicationAr: "قاطع رئيسي كبير", price: 30 },
  { rating: 160, typicalApplication: "Inverter AC output", typicalApplicationAr: "مخرج العاكس AC", price: 40 },
  { rating: 200, typicalApplication: "Large inverter", typicalApplicationAr: "عاكس كبير", price: 50 },
  { rating: 250, typicalApplication: "Commercial main", typicalApplicationAr: "قاطع تجاري رئيسي", price: 65 },
  { rating: 315, typicalApplication: "Industrial main", typicalApplicationAr: "قاطع صناعي رئيسي", price: 80 },
];

export const dcBreakerSpecs: BreakerSpec[] = [
  { rating: 10, typicalApplication: "String fuse", typicalApplicationAr: "فيوز سلسلة ألواح", price: 8 },
  { rating: 16, typicalApplication: "String protection", typicalApplicationAr: "حماية سلسلة ألواح", price: 10 },
  { rating: 20, typicalApplication: "PV combiner", typicalApplicationAr: "صندوق تجميع PV", price: 12 },
  { rating: 25, typicalApplication: "PV combiner medium", typicalApplicationAr: "صندوق تجميع متوسط", price: 15 },
  { rating: 32, typicalApplication: "Battery fuse", typicalApplicationAr: "فيوز بطاريات", price: 18 },
  { rating: 50, typicalApplication: "Battery breaker", typicalApplicationAr: "قاطع بطاريات", price: 25 },
  { rating: 63, typicalApplication: "Battery bank", typicalApplicationAr: "بنك بطاريات", price: 30 },
  { rating: 80, typicalApplication: "Large battery bank", typicalApplicationAr: "بنك بطاريات كبير", price: 40 },
  { rating: 100, typicalApplication: "Industrial battery", typicalApplicationAr: "بطاريات صناعية", price: 50 },
  { rating: 125, typicalApplication: "Industrial battery large", typicalApplicationAr: "بطاريات صناعية كبيرة", price: 65 },
  { rating: 160, typicalApplication: "Large DC system", typicalApplicationAr: "نظام تيار مستمر كبير", price: 80 },
  { rating: 200, typicalApplication: "Very large DC", typicalApplicationAr: "نظام تيار مستمر كبير جداً", price: 100 },
];

export const dieselGeneratorData = {
  fuelConsumptionPerKWh: 0.3,
  dieselPricePerLiter: 0.8,
  maintenancePerKWh: 0.03,
  generatorPricePerKW: 200,
  generatorLifetime: 15000,
  efficiency: 0.35,
};

export const monthNamesAr = [
  "يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو",
  "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"
];

export const monthNamesEn = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
];

// ============= TRANSLATIONS =============
export const translations: Record<string, Record<string, string>> = {
  ar: {
    // App
    "app.title": "حاسبة المنظومة الشمسية",
    "app.subtitle": "أداة احترافية لتصميم وحساب المنظومات الشمسية الكهروضوئية",
    "badge.accurate": "دقيق",
    "badge.instant": "فوري",
    "dark.toggle": "فاتح",
    "light.toggle": "داكن",

    // Tabs
    "tab.calculator": "الحاسبة",
    "tab.cables": "الكابلات",
    "tab.economics": "الاقتصاد",
    "tab.bom": "المواد",
    "tab.guidelines": "الإرشادات",
    "tab.save": "الحفظ",

    // Project
    "project.title": "معلومات المشروع",
    "project.desc": "أدخل معلومات المشروع الأساسية (اختياري)",
    "project.show": "عرض",
    "project.hide": "إخفاء",
    "project.name": "اسم المشروع",
    "project.client": "اسم العميل",
    "project.location": "الموقع",
    "project.engineer": "اسم المهندس",
    "project.number": "رقم المشروع",
    "project.date": "التاريخ",
    "project.notes": "ملاحظات",

    // Location
    "location.title": "الموقع والإشعاع الشمسي",
    "location.country": "الدولة",
    "location.selectCountry": "اختر الدولة",
    "location.governorate": "المدينة/المحافظة",
    "location.select": "اختر المدينة",
    "location.customLocation": "موقع مخصص",
    "location.latitude": "خط العرض",
    "location.longitude": "خط الطول",
    "location.useMyLocation": "استخدم موقعي",
    "location.detecting": "جارٍ التحديد...",
    "location.customHint": "أدخل الإحداثيات الجغرافية لحساب الإشعاع الشمسي",
    "location.annualAvg": "المعدل السنوي",
    "location.peakSunHours": "ساعات الشمس الذروية",
    "location.tiltAngle": "زاوية الميل المثلى",
    "location.autoFill": "تعبئة تلقائية",

    // Load
    "load.title": "الأحمال الكهربائية",
    "load.residential": "منزلي",
    "load.industrial": "صناعي",
    "load.add": "إضافة حمل",
    "load.name": "الجهاز",
    "load.quantity": "العدد",
    "load.power": "القدرة (W)",
    "load.hours": "الساعات",
    "load.total": "المجموع",
    "load.peakLoad": "الحمل الذروي",
    "load.dailyEnergy": "الطاقة اليومية",

    // Parameters
    "params.title": "معلمات المنظومة",
    "params.systemType": "نوع المنظومة",
    "params.onGrid": "متصلة بالشبكة (On-Grid)",
    "params.offGrid": "مستقلة (Off-Grid)",
    "params.hybrid": "هجينة (Hybrid)",
    "params.sunshine": "ساعات الشمس",
    "params.voltage": "جهد النظام",
    "params.backup": "أيام الاحتياطي",
    "params.panelWattage": "قدرة اللوح",
    "params.batteryType": "نوع البطارية",
    "params.leadAcid": "حمض الرصاص",
    "params.lithium": "ليثيوم",
    "params.batteryCapacity": "سعة البطارية",
    "params.batteryVoltage": "جهد البطارية",
    "params.dod": "عمق التفريغ (DoD)",
    "params.efficiency": "كفاءة النظام",
    "params.inverterEfficiency": "كفاءة العاكس",
    "panel.title": "مواصفات اللوح",

    // Calculate
    "calc.button": "احسب المنظومة الشمسية",

    // Results
    "results.title": "نتائج الحساب",
    "results.loadSummary": "ملخص الأحمال",
    "results.peakLoad": "الحمل الذروي",
    "results.dailyConsumption": "الاستهلاك اليومي",
    "results.monthlyConsumption": "الاستهلاك الشهري",
    "results.solarPanels": "الألواح الشمسية",
    "results.requiredCapacity": "القدرة المطلوبة",
    "results.numberOfPanels": "عدد الألواح",
    "results.panelArea": "المساحة المطلوبة",
    "results.batteryBank": "بنك البطاريات",
    "results.usableStorage": "التخزين القابل للاستخدام",
    "results.totalBatteries": "إجمالي البطاريات",
    "results.series": "توالي",
    "results.parallel": "توازي",
    "results.storedEnergy": "الطاقة المخزنة",
    "results.inverter": "العاكس (الإنفرتر)",
    "results.inverterCapacity": "قدرة العاكس",
    "results.recommended": "الموصى به",
    "results.controller": "منظم الشحن",
    "results.controllerCurrent": "تيار المنظم",
    "results.recommendedController": "المنظم الموصى به",
    "results.controllerType": "نوع المنظم",
    "results.cost": "التكلفة التقديرية",
    "results.panelsCost": "تكلفة الألواح",
    "results.batteriesCost": "تكلفة البطاريات",
    "results.inverterCost": "تكلفة العاكس",
    "results.controllerCost": "تكلفة المنظم",
    "results.accessories": "الملحقات والتركيب",
    "results.totalCost": "التكلفة الإجمالية",
    "results.mpptString": "توصيل سلاسل الألواح (MPPT)",
    "results.panelsPerString": "ألواح لكل سلسلة",
    "results.totalStrings": "عدد السلاسل",
    "results.stringsPerMPPT": "سلاسل لكل MPPT",
    "results.stringVoc": "جهد السلسلة المفتوح",
    "results.stringVmp": "جهد السلسلة الأقصى",
    "results.stringPower": "قدرة السلسلة",

    // Cables
    "cables.title": "الكابلات والحماية الكهربائية",
    "cables.pvStringCable": "كابل سلسلة الألواح",
    "cables.pvMainCable": "الكابل الرئيسي PV",
    "cables.batteryCable": "كابل البطاريات",
    "cables.acOutputCable": "كابل مخرج AC",
    "cables.acMainCable": "الكابل الرئيسي AC",
    "cables.current": "التيار",
    "cables.recommendedSize": "المقطع الموصى",
    "cables.voltageDrop": "هبوط الجهد",
    "cables.voltageDropPercent": "نسبة الهبوط",
    "cables.status": "الحالة",
    "cables.ok": "مقبول",
    "cables.high": "مرتفع",
    "cables.circuitBreaker": "القواطع الكهربائية",
    "cables.breakerRating": "تصنيف القاطع",
    "cables.breakerType": "النوع",
    "cables.breakerForPV": "سلسلة ألواح",
    "cables.breakerForBattery": "بطاريات",
    "cables.breakerForAC": "مخرج عاكس",
    "cables.breakerForMainAC": "رئيسي AC",
    "cables.grounding": "التأريض",
    "cables.groundingRod": "قضيب التأريض",
    "cables.groundingConductor": "موصل التأريض",
    "cables.groundingResistance": "مقاومة التأريض",

    // Economics
    "econ.annualProduction": "الإنتاج السنوي",
    "econ.kwhPerYear": "كيلوواط ساعة/سنة",
    "econ.lcoe": "تكلفة الطاقة المساوية (LCOE)",
    "econ.paybackPeriod": "فترة الاسترداد",
    "econ.years": "سنة",
    "econ.months": "شهر",
    "econ.totalInvestment": "إجمالي الاستثمار",
    "econ.usdPerKWh": "$/كيلوواط ساعة",
    "econ.usdPerYear": "$/سنة",
    "econ.monthlyProduction": "الإنتاج الشهري المتوقع",
    "econ.dieselComparison": "مقارنة مع الديزل",
    "econ.dieselCost": "تكلفة الديزل السنوية",
    "econ.dieselSavings": "التوفير مقابل الديزل",
    "econ.gridComparison": "مقارنة مع الشبكة",
    "econ.gridCost": "تكلفة الشبكة السنوية",
    "econ.gridSavings": "التوفير مقابل الشبكة",
    "econ.co2Saved": "تقليل CO₂",
    "econ.financing": "حاسبة التمويل",
    "econ.loanAmount": "مبلغ القرض",
    "econ.interestRate": "نسبة الفائدة",
    "econ.loanTerm": "مدة القرض (سنوات)",
    "econ.monthlyPayment": "القسط الشهري",
    "econ.totalInterest": "إجمالي الفوائد",

    // BOM
    "bom.title": "قائمة المواد (BOM)",
    "bom.description": "الوصف",
    "bom.quantity": "الكمية",
    "bom.unit": "الوحدة",
    "bom.unitPrice": "سعر الوحدة",
    "bom.totalPrice": "السعر الإجمالي",
    "bom.notes": "ملاحظات",

    // Save
    "save.saveCurrent": "حفظ المشروع الحالي",
    "save.savedProjects": "المشاريع المحفوظة",
    "save.noProjects": "لا توجد مشاريع محفوظة",
    "save.load": "تحميل",
    "save.delete": "حذف",
    "save.export": "تصدير",
    "save.import": "استيراد",

    // Actions
    "action.pdf": "تصدير PDF",
    "action.share": "مشاركة",
    "action.print": "طباعة",

    // Units
    "unit.watt": "واط",
    "unit.kwh": "كيلوواط ساعة",
    "unit.amp": "أمبير",
    "unit.volt": "فولت",
    "unit.hours": "ساعة",
    "unit.day": "يوم",
    "unit.degrees": "درجة",
    "unit.percent": "%",
    "unit.localCurrency": "عملة محلية",

    // Guidelines
    "guidelines.title": "إرشادات التركيب والتوصيات",
    "guidelines.diagram": "مخطط النظام",
    "guidelines.installation": "إرشادات التركيب",
    "guidelines.recommendations": "التوصيات",
    "guidelines.critical": "حرج",
    "guidelines.important": "مهم",
    "guidelines.recommended": "موصى به",
    "guidelines.viewGuidelines": "عرض الإرشادات والمخططات",

    // AI Assistant
    "ai.title": "مساعد الذكاء الاصطناعي",
    "ai.placeholder": "اسأل عن المنظومة الشمسية...",
    "ai.suggestedQuestions": "أسئلة مقترحة",
    "ai.thinking": "جارٍ التفكير...",
    "ai.error": "حدث خطأ، حاول مرة أخرى",
    "ai.welcome": "مرحباً! أنا مساعدك المتخصص في المنظومات الشمسية. كيف يمكنني مساعدتك؟",
  },
  en: {
    // App
    "app.title": "Solar System Calculator",
    "app.subtitle": "Professional tool for PV solar system design and calculation",
    "badge.accurate": "Accurate",
    "badge.instant": "Instant",
    "dark.toggle": "Light",
    "light.toggle": "Dark",

    // Tabs
    "tab.calculator": "Calculator",
    "tab.cables": "Cables",
    "tab.economics": "Economics",
    "tab.bom": "BOM",
    "tab.guidelines": "Guidelines",
    "tab.save": "Save",

    // Project
    "project.title": "Project Information",
    "project.desc": "Enter basic project information (optional)",
    "project.show": "Show",
    "project.hide": "Hide",
    "project.name": "Project Name",
    "project.client": "Client Name",
    "project.location": "Location",
    "project.engineer": "Engineer Name",
    "project.number": "Project Number",
    "project.date": "Date",
    "project.notes": "Notes",

    // Location
    "location.title": "Location & Solar Radiation",
    "location.country": "Country",
    "location.selectCountry": "Select Country",
    "location.governorate": "City/Governorate",
    "location.select": "Select City",
    "location.customLocation": "Custom Location",
    "location.latitude": "Latitude",
    "location.longitude": "Longitude",
    "location.useMyLocation": "Use My Location",
    "location.detecting": "Detecting...",
    "location.customHint": "Enter coordinates to calculate solar radiation",
    "location.annualAvg": "Annual Average",
    "location.peakSunHours": "Peak Sun Hours",
    "location.tiltAngle": "Optimal Tilt Angle",
    "location.autoFill": "Auto Fill",

    // Load
    "load.title": "Electrical Loads",
    "load.residential": "Residential",
    "load.industrial": "Industrial",
    "load.add": "Add Load",
    "load.name": "Device",
    "load.quantity": "Qty",
    "load.power": "Power (W)",
    "load.hours": "Hours",
    "load.total": "Total",
    "load.peakLoad": "Peak Load",
    "load.dailyEnergy": "Daily Energy",

    // Parameters
    "params.title": "System Parameters",
    "params.systemType": "System Type",
    "params.onGrid": "Grid-Tied (On-Grid)",
    "params.offGrid": "Off-Grid",
    "params.hybrid": "Hybrid",
    "params.sunshine": "Sunshine Hours",
    "params.voltage": "System Voltage",
    "params.backup": "Backup Days",
    "params.panelWattage": "Panel Wattage",
    "params.batteryType": "Battery Type",
    "params.leadAcid": "Lead-Acid",
    "params.lithium": "Lithium",
    "params.batteryCapacity": "Battery Capacity",
    "params.batteryVoltage": "Battery Voltage",
    "params.dod": "Depth of Discharge (DoD)",
    "params.efficiency": "System Efficiency",
    "params.inverterEfficiency": "Inverter Efficiency",
    "panel.title": "Panel Specifications",

    // Calculate
    "calc.button": "Calculate Solar System",

    // Results
    "results.title": "Calculation Results",
    "results.loadSummary": "Load Summary",
    "results.peakLoad": "Peak Load",
    "results.dailyConsumption": "Daily Consumption",
    "results.monthlyConsumption": "Monthly Consumption",
    "results.solarPanels": "Solar Panels",
    "results.requiredCapacity": "Required Capacity",
    "results.numberOfPanels": "Number of Panels",
    "results.panelArea": "Required Area",
    "results.batteryBank": "Battery Bank",
    "results.usableStorage": "Usable Storage",
    "results.totalBatteries": "Total Batteries",
    "results.series": "Series",
    "results.parallel": "Parallel",
    "results.storedEnergy": "Stored Energy",
    "results.inverter": "Inverter",
    "results.inverterCapacity": "Inverter Capacity",
    "results.recommended": "Recommended",
    "results.controller": "Charge Controller",
    "results.controllerCurrent": "Controller Current",
    "results.recommendedController": "Recommended Controller",
    "results.controllerType": "Controller Type",
    "results.cost": "Cost Estimate",
    "results.panelsCost": "Panels Cost",
    "results.batteriesCost": "Batteries Cost",
    "results.inverterCost": "Inverter Cost",
    "results.controllerCost": "Controller Cost",
    "results.accessories": "Accessories & Installation",
    "results.totalCost": "Total Cost",
    "results.mpptString": "MPPT String Configuration",
    "results.panelsPerString": "Panels Per String",
    "results.totalStrings": "Total Strings",
    "results.stringsPerMPPT": "Strings Per MPPT",
    "results.stringVoc": "String Voc",
    "results.stringVmp": "String Vmp",
    "results.stringPower": "String Power",

    // Cables
    "cables.title": "Cables & Electrical Protection",
    "cables.pvStringCable": "PV String Cable",
    "cables.pvMainCable": "PV Main Cable",
    "cables.batteryCable": "Battery Cable",
    "cables.acOutputCable": "AC Output Cable",
    "cables.acMainCable": "AC Main Cable",
    "cables.current": "Current",
    "cables.recommendedSize": "Recommended Size",
    "cables.voltageDrop": "Voltage Drop",
    "cables.voltageDropPercent": "Drop %",
    "cables.status": "Status",
    "cables.ok": "OK",
    "cables.high": "High",
    "cables.circuitBreaker": "Circuit Breakers",
    "cables.breakerRating": "Breaker Rating",
    "cables.breakerType": "Type",
    "cables.breakerForPV": "PV String",
    "cables.breakerForBattery": "Battery",
    "cables.breakerForAC": "Inverter AC Out",
    "cables.breakerForMainAC": "Main AC",
    "cables.grounding": "Grounding",
    "cables.groundingRod": "Grounding Rod",
    "cables.groundingConductor": "Grounding Conductor",
    "cables.groundingResistance": "Grounding Resistance",

    // Economics
    "econ.annualProduction": "Annual Production",
    "econ.kwhPerYear": "kWh/year",
    "econ.lcoe": "Levelized Cost (LCOE)",
    "econ.paybackPeriod": "Payback Period",
    "econ.years": "years",
    "econ.months": "months",
    "econ.totalInvestment": "Total Investment",
    "econ.usdPerKWh": "$/kWh",
    "econ.usdPerYear": "$/year",
    "econ.monthlyProduction": "Monthly Production Forecast",
    "econ.dieselComparison": "Diesel Comparison",
    "econ.dieselCost": "Annual Diesel Cost",
    "econ.dieselSavings": "Savings vs Diesel",
    "econ.gridComparison": "Grid Comparison",
    "econ.gridCost": "Annual Grid Cost",
    "econ.gridSavings": "Savings vs Grid",
    "econ.co2Saved": "CO₂ Reduction",
    "econ.financing": "Financing Calculator",
    "econ.loanAmount": "Loan Amount",
    "econ.interestRate": "Interest Rate",
    "econ.loanTerm": "Loan Term (years)",
    "econ.monthlyPayment": "Monthly Payment",
    "econ.totalInterest": "Total Interest",

    // BOM
    "bom.title": "Bill of Materials (BOM)",
    "bom.description": "Description",
    "bom.quantity": "Quantity",
    "bom.unit": "Unit",
    "bom.unitPrice": "Unit Price",
    "bom.totalPrice": "Total Price",
    "bom.notes": "Notes",

    // Save
    "save.saveCurrent": "Save Current Project",
    "save.savedProjects": "Saved Projects",
    "save.noProjects": "No saved projects",
    "save.load": "Load",
    "save.delete": "Delete",
    "save.export": "Export",
    "save.import": "Import",

    // Actions
    "action.pdf": "Export PDF",
    "action.share": "Share",
    "action.print": "Print",

    // Units
    "unit.watt": "W",
    "unit.kwh": "kWh",
    "unit.amp": "A",
    "unit.volt": "V",
    "unit.hours": "hrs",
    "unit.day": "day(s)",
    "unit.degrees": "°",
    "unit.percent": "%",
    "unit.localCurrency": "Local Currency",

    // Guidelines
    "guidelines.title": "Installation Guidelines & Recommendations",
    "guidelines.diagram": "System Diagram",
    "guidelines.installation": "Installation Guidelines",
    "guidelines.recommendations": "Recommendations",
    "guidelines.critical": "Critical",
    "guidelines.important": "Important",
    "guidelines.recommended": "Recommended",
    "guidelines.viewGuidelines": "View Guidelines & Diagrams",

    // AI Assistant
    "ai.title": "AI Assistant",
    "ai.placeholder": "Ask about solar systems...",
    "ai.suggestedQuestions": "Suggested Questions",
    "ai.thinking": "Thinking...",
    "ai.error": "An error occurred, try again",
    "ai.welcome": "Hello! I'm your solar system specialist assistant. How can I help you?",
  },
};
