// Solar radiation data for Yemeni governorates (kWh/m²/day - annual average)
export interface SolarRadiationData {
  name: string;
  nameEn: string;
  latitude: number;
  annualAvg: number;
  monthly: number[]; // Jan-Dec kWh/m²/day
  optimalTiltAngle: number; // degrees
  peakSunHours: number; // annual average PSH
}

export const yemenGovernorates: SolarRadiationData[] = [
  { name: "صنعاء", nameEn: "Sana'a", latitude: 15.35, annualAvg: 5.8, monthly: [5.2, 5.8, 6.5, 6.8, 6.6, 6.4, 5.8, 5.5, 5.9, 5.6, 5.3, 5.0], optimalTiltAngle: 15, peakSunHours: 6.0 },
  { name: "عدن", nameEn: "Aden", latitude: 12.78, annualAvg: 6.2, monthly: [5.8, 6.3, 6.8, 6.9, 6.7, 5.9, 5.4, 5.3, 5.8, 6.1, 6.0, 5.7], optimalTiltAngle: 13, peakSunHours: 6.3 },
  { name: "تعز", nameEn: "Taiz", latitude: 13.58, annualAvg: 6.0, monthly: [5.5, 6.0, 6.6, 6.8, 6.5, 5.8, 5.2, 5.1, 5.6, 5.9, 5.8, 5.4], optimalTiltAngle: 14, peakSunHours: 6.1 },
  { name: "الحديدة", nameEn: "Al Hudaydah", latitude: 14.80, annualAvg: 6.1, monthly: [5.6, 6.1, 6.7, 7.0, 6.8, 6.2, 5.5, 5.2, 5.5, 5.8, 5.7, 5.4], optimalTiltAngle: 15, peakSunHours: 6.2 },
  { name: "إب", nameEn: "Ibb", latitude: 13.97, annualAvg: 5.7, monthly: [5.2, 5.6, 6.2, 6.4, 6.0, 5.3, 4.8, 4.7, 5.2, 5.5, 5.4, 5.1], optimalTiltAngle: 14, peakSunHours: 5.8 },
  { name: "ذمار", nameEn: "Dhamar", latitude: 14.54, annualAvg: 5.9, monthly: [5.4, 5.9, 6.5, 6.7, 6.4, 5.9, 5.4, 5.2, 5.6, 5.7, 5.5, 5.2], optimalTiltAngle: 15, peakSunHours: 6.0 },
  { name: "حضرموت", nameEn: "Hadhramaut", latitude: 15.94, annualAvg: 6.4, monthly: [6.0, 6.5, 7.0, 7.2, 7.0, 6.8, 6.2, 5.9, 6.3, 6.2, 6.0, 5.8], optimalTiltAngle: 16, peakSunHours: 6.5 },
  { name: "المكلا", nameEn: "Al Mukalla", latitude: 14.53, annualAvg: 6.3, monthly: [5.9, 6.4, 6.9, 7.1, 6.9, 6.5, 5.8, 5.5, 5.9, 6.0, 5.9, 5.7], optimalTiltAngle: 15, peakSunHours: 6.4 },
  { name: "مأرب", nameEn: "Marib", latitude: 15.47, annualAvg: 6.5, monthly: [6.1, 6.6, 7.2, 7.4, 7.2, 7.0, 6.5, 6.2, 6.5, 6.3, 6.1, 5.9], optimalTiltAngle: 16, peakSunHours: 6.6 },
  { name: "شبوة", nameEn: "Shabwah", latitude: 14.55, annualAvg: 6.2, monthly: [5.8, 6.3, 6.8, 7.0, 6.8, 6.4, 5.7, 5.4, 5.8, 5.9, 5.8, 5.6], optimalTiltAngle: 15, peakSunHours: 6.3 },
  { name: "أبين", nameEn: "Abyan", latitude: 13.48, annualAvg: 6.1, monthly: [5.7, 6.2, 6.7, 6.9, 6.6, 6.0, 5.4, 5.2, 5.7, 5.9, 5.8, 5.5], optimalTiltAngle: 13, peakSunHours: 6.2 },
  { name: "لحج", nameEn: "Lahij", latitude: 13.06, annualAvg: 6.0, monthly: [5.6, 6.1, 6.6, 6.8, 6.5, 5.8, 5.3, 5.1, 5.6, 5.8, 5.7, 5.4], optimalTiltAngle: 13, peakSunHours: 6.1 },
  { name: "الضالع", nameEn: "Al Dhale", latitude: 13.70, annualAvg: 5.8, monthly: [5.3, 5.8, 6.4, 6.6, 6.2, 5.5, 5.0, 4.9, 5.3, 5.6, 5.5, 5.2], optimalTiltAngle: 14, peakSunHours: 5.9 },
  { name: "البيضاء", nameEn: "Al Bayda", latitude: 14.45, annualAvg: 5.9, monthly: [5.4, 5.9, 6.5, 6.7, 6.4, 5.9, 5.4, 5.2, 5.6, 5.7, 5.5, 5.2], optimalTiltAngle: 14, peakSunHours: 6.0 },
  { name: "صعدة", nameEn: "Sa'dah", latitude: 16.94, annualAvg: 5.7, monthly: [5.1, 5.7, 6.4, 6.7, 6.5, 6.3, 5.8, 5.5, 5.8, 5.5, 5.2, 4.9], optimalTiltAngle: 17, peakSunHours: 5.9 },
  { name: "عمران", nameEn: "Amran", latitude: 15.63, annualAvg: 5.8, monthly: [5.2, 5.8, 6.5, 6.8, 6.6, 6.3, 5.7, 5.4, 5.8, 5.6, 5.3, 5.0], optimalTiltAngle: 16, peakSunHours: 6.0 },
  { name: "حجة", nameEn: "Hajjah", latitude: 15.70, annualAvg: 5.6, monthly: [5.0, 5.6, 6.3, 6.6, 6.3, 6.0, 5.5, 5.2, 5.5, 5.4, 5.1, 4.8], optimalTiltAngle: 16, peakSunHours: 5.8 },
  { name: "المهويت", nameEn: "Al Mahwit", latitude: 15.47, annualAvg: 5.7, monthly: [5.1, 5.7, 6.4, 6.7, 6.4, 6.1, 5.6, 5.3, 5.6, 5.5, 5.2, 4.9], optimalTiltAngle: 15, peakSunHours: 5.9 },
  { name: "ريمة", nameEn: "Raymah", latitude: 14.62, annualAvg: 5.6, monthly: [5.1, 5.6, 6.2, 6.4, 6.1, 5.5, 5.0, 4.9, 5.3, 5.4, 5.2, 4.9], optimalTiltAngle: 15, peakSunHours: 5.7 },
  { name: "سقطرى", nameEn: "Socotra", latitude: 12.46, annualAvg: 6.0, monthly: [5.6, 6.1, 6.6, 6.8, 6.5, 5.7, 5.2, 5.0, 5.5, 5.8, 5.7, 5.4], optimalTiltAngle: 12, peakSunHours: 6.1 },
  { name: "الجوف", nameEn: "Al Jawf", latitude: 16.08, annualAvg: 6.1, monthly: [5.5, 6.1, 6.8, 7.1, 6.9, 6.7, 6.2, 5.8, 6.1, 5.9, 5.6, 5.3], optimalTiltAngle: 16, peakSunHours: 6.2 },
  { name: "صالح", nameEn: "Saleh", latitude: 15.35, annualAvg: 5.9, monthly: [5.4, 5.9, 6.5, 6.8, 6.5, 6.2, 5.7, 5.4, 5.7, 5.7, 5.4, 5.1], optimalTiltAngle: 15, peakSunHours: 6.0 },
];

// Cable specifications for solar installations
export interface CableSpec {
  crossSection: number; // mm²
  maxCurrentAC: number; // Amps for AC
  maxCurrentDC: number; // Amps for DC
  resistancePerKm: number; // ohm/km (copper)
  voltageDropPerAmpPerKm: number; // V/A/km at 0.8 PF for AC, resistive for DC
  pricePerMeter: number; // USD/m approximate
}

export const cableSpecs: CableSpec[] = [
  { crossSection: 1.5, maxCurrentAC: 14, maxCurrentDC: 12, resistancePerKm: 12.1, voltageDropPerAmpPerKm: 0.025, pricePerMeter: 0.3 },
  { crossSection: 2.5, maxCurrentAC: 19, maxCurrentDC: 16, resistancePerKm: 7.41, voltageDropPerAmpPerKm: 0.016, pricePerMeter: 0.5 },
  { crossSection: 4, maxCurrentAC: 26, maxCurrentDC: 22, resistancePerKm: 4.61, voltageDropPerAmpPerKm: 0.010, pricePerMeter: 0.7 },
  { crossSection: 6, maxCurrentAC: 34, maxCurrentDC: 29, resistancePerKm: 3.08, voltageDropPerAmpPerKm: 0.0064, pricePerMeter: 1.0 },
  { crossSection: 10, maxCurrentAC: 48, maxCurrentDC: 40, resistancePerKm: 1.83, voltageDropPerAmpPerKm: 0.0038, pricePerMeter: 1.5 },
  { crossSection: 16, maxCurrentAC: 65, maxCurrentDC: 54, resistancePerKm: 1.15, voltageDropPerAmpPerKm: 0.0024, pricePerMeter: 2.2 },
  { crossSection: 25, maxCurrentAC: 85, maxCurrentDC: 71, resistancePerKm: 0.727, voltageDropPerAmpPerKm: 0.0015, pricePerMeter: 3.5 },
  { crossSection: 35, maxCurrentAC: 105, maxCurrentDC: 88, resistancePerKm: 0.524, voltageDropPerAmpPerKm: 0.0011, pricePerMeter: 4.5 },
  { crossSection: 50, maxCurrentAC: 130, maxCurrentDC: 110, resistancePerKm: 0.387, voltageDropPerAmpPerKm: 0.00081, pricePerMeter: 6.0 },
  { crossSection: 70, maxCurrentAC: 170, maxCurrentDC: 140, resistancePerKm: 0.268, voltageDropPerAmpPerKm: 0.00056, pricePerMeter: 8.5 },
  { crossSection: 95, maxCurrentAC: 210, maxCurrentDC: 175, resistancePerKm: 0.193, voltageDropPerAmpPerKm: 0.00040, pricePerMeter: 12.0 },
  { crossSection: 120, maxCurrentAC: 245, maxCurrentDC: 200, resistancePerKm: 0.153, voltageDropPerAmpPerKm: 0.00032, pricePerMeter: 15.0 },
];

// Circuit breaker / Fuse ratings
export interface BreakerSpec {
  rating: number; // Amps
  typicalApplication: string;
  typicalApplicationAr: string;
  price: number; // USD approximate
}

export const breakerSpecs: BreakerSpec[] = [
  { rating: 6, typicalApplication: "Lighting circuits", typicalApplicationAr: "دوائر الإضاءة", price: 3 },
  { rating: 10, typicalApplication: "Small loads", typicalApplicationAr: "أحمال صغيرة", price: 3 },
  { rating: 16, typicalApplication: "General outlets", typicalApplicationAr: "مقابس عامة", price: 4 },
  { rating: 20, typicalApplication: "Medium loads", typicalApplicationAr: "أحمال متوسطة", price: 5 },
  { rating: 25, typicalApplication: "AC units small", typicalApplicationAr: "تكييفات صغيرة", price: 6 },
  { rating: 32, typicalApplication: "AC units medium", typicalApplicationAr: "تكييفات متوسطة", price: 7 },
  { rating: 40, typicalApplication: "Sub-panels", typicalApplicationAr: "لوحات فرعية", price: 10 },
  { rating: 50, typicalApplication: "Large loads", typicalApplicationAr: "أحمال كبيرة", price: 12 },
  { rating: 63, typicalApplication: "Main breaker small", typicalApplicationAr: "قاطع رئيسي صغير", price: 15 },
  { rating: 80, typicalApplication: "Main breaker medium", typicalApplicationAr: "قاطع رئيسي متوسط", price: 20 },
  { rating: 100, typicalApplication: "Main breaker", typicalApplicationAr: "قاطع رئيسي", price: 25 },
  { rating: 125, typicalApplication: "Main breaker large", typicalApplicationAr: "قاطع رئيسي كبير", price: 30 },
  { rating: 160, typicalApplication: "Inverter AC output", typicalApplicationAr: "مخرج العاكس AC", price: 40 },
  { rating: 200, typicalApplication: "Large inverter", typicalApplicationAr: "عاكس كبير", price: 50 },
  { rating: 250, typicalApplication: "Commercial main", typicalApplicationAr: "قاطع تجاري رئيسي", price: 65 },
  { rating: 315, typicalApplication: "Industrial main", typicalApplicationAr: "قاطع صناعي رئيسي", price: 80 },
];

// DC Fuse / DC Breaker ratings for solar
export const dcBreakerSpecs: BreakerSpec[] = [
  { rating: 10, typicalApplication: "String fuse", typicalApplicationAr: "فيوز سلسلة ألواح", price: 8 },
  { rating: 16, typicalApplication: "String protection", typicalApplicationAr: "حماية سلسلة ألواح", price: 10 },
  { rating: 20, typicalApplication: "PV combiner", typicalApplicationAr: "صندوق تجميع PV", price: 12 },
  { rating: 25, typicalApplication: "PV combiner medium", typicalApplicationAr: "صندوق تجميع متوسط", price: 15 },
  { rating: 32, typicalApplication: "Battery fuse", typicalApplicationAr: "فيوز بطاريات", price: 18 },
  { rating: 50, typicalApplication: "Battery breaker", typicalApplicationAr: "قاطع بطاريات", price: 25 },
  { rating: 63, typicalApplication: "Battery bank", typicalApplicationAr: "بنك بطاريات", price: 30 },
  { rating: 80, typicalApplication: "Large battery bank", typicalApplicationAr: "بنك بطاريات كبير", price: 40 },
  { rating: 100, typicalApplication: "Industrial battery", typicalApplicationAr: "بطاريات صناعية", price: 50 },
  { rating: 125, typicalApplication: "Industrial battery large", typicalApplicationAr: "بطاريات صناعية كبيرة", price: 65 },
  { rating: 160, typicalApplication: "Large DC system", typicalApplicationAr: "نظام تيار مستمر كبير", price: 80 },
  { rating: 200, typicalApplication: "Very large DC", typicalApplicationAr: "نظام تيار مستمر كبير جداً", price: 100 },
];

// Diesel generator comparison data
export const dieselGeneratorData = {
  fuelConsumptionPerKWh: 0.3, // liters per kWh
  dieselPricePerLiter: 0.8, // USD per liter in Yemen (subsidized)
  maintenancePerKWh: 0.03, // USD per kWh
  generatorPricePerKW: 200, // USD per kW installed
  generatorLifetime: 15000, // hours
  efficiency: 0.35, // typical diesel generator efficiency
};

// Monthly Arabic names
export const monthNamesAr = [
  "يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو",
  "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"
];

export const monthNamesEn = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
];

// Translation dictionaries
export const translations: Record<string, Record<string, string>> = {
  ar: {
    // Header
    "app.title": "حاسبة المنظومة الشمسية",
    "app.subtitle": "احسب مكونات منظومتك الشمسية بدقة واحترافية",
    "badge.accurate": "حساب دقيق",
    "badge.instant": "نتائج فورية",
    // Tabs
    "tab.calculator": "الحاسبة",
    "tab.cables": "الكابلات والحماية",
    "tab.economics": "التحليل الاقتصادي",
    "tab.bom": "قائمة المواد BOM",
    "tab.save": "حفظ المشاريع",
    // Project Info
    "project.title": "معلومات المشروع",
    "project.desc": "أدخل معلومات المشروع لتضمينها في التقرير",
    "project.name": "اسم المشروع",
    "project.client": "اسم العميل",
    "project.location": "الموقع",
    "project.date": "التاريخ",
    "project.engineer": "اسم المهندس",
    "project.number": "رقم المشروع",
    "project.notes": "ملاحظات",
    "project.show": "عرض",
    "project.hide": "إخفاء",
    // Location & Solar
    "location.title": "الموقع والإشعاع الشمسي",
    "location.governorate": "المحافظة",
    "location.select": "اختر المحافظة",
    "location.annualAvg": "متوسط الإشعاع السنوي",
    "location.peakSunHours": "ساعات الشمس الذروية",
    "location.tiltAngle": "زاوية الميل المثلى",
    "location.latitude": "خط العرض",
    "location.autoFill": "تعبئة تلقائية لساعات الشمس",
    // Load
    "load.title": "جدول الأحمال الكهربائية",
    "load.type": "نوع الحمل",
    "load.residential": "سكني",
    "load.industrial": "صناعي",
    "load.name": "اسم الجهاز",
    "load.quantity": "العدد",
    "load.power": "الاستطاعة (واط)",
    "load.hours": "ساعات التشغيل/يوم",
    "load.total": "الإجمالي (واط·س)",
    "load.add": "إضافة حمل",
    "load.peakLoad": "ذروة الحمل",
    "load.dailyEnergy": "الطاقة اليومية",
    // System Params
    "params.title": "معلمات النظام",
    "params.sunshine": "ساعات سطوع الشمس",
    "params.voltage": "جهد النظام (فولت)",
    "params.backup": "أيام الاحتياطي",
    "params.panelWattage": "استطاعة اللوح (واط)",
    "params.systemType": "نوع النظام",
    "params.onGrid": "متصلة بالشبكة (On-Grid)",
    "params.offGrid": "مستقلة (Off-Grid)",
    "params.hybrid": "هجينة (Hybrid)",
    "params.batteryType": "نوع البطارية",
    "params.leadAcid": "حمض الرصاص",
    "params.lithium": "ليثيوم (LiFePO4)",
    "params.batteryCapacity": "سعة البطارية (أمبير·ساعة)",
    "params.batteryVoltage": "جهد البطارية (فولت)",
    "params.dod": "عمق التفريغ (DoD %)",
    "params.efficiency": "كفاءة النظام (%)",
    "params.inverterEfficiency": "كفاءة العاكس (%)",
    // Panel Specs
    "panel.title": "مواصفات اللوح الشمسي",
    "panel.voc": "جهد الدائرة المفتوحة Voc (فولت)",
    "panel.isc": "تيار القصر Isc (أمبير)",
    "panel.vmp": "جهد أقصى قدرة Vmp (فولت)",
    "panel.imp": "تيار أقصى قدرة Imp (أمبير)",
    // Calculate
    "calc.button": "احسب المنظومة",
    // Results
    "results.title": "نتائج الحساب",
    "results.loadSummary": "ملخص الأحمال",
    "results.peakLoad": "ذروة الحمل",
    "results.dailyConsumption": "الاستهلاك اليومي",
    "results.monthlyConsumption": "الاستهلاك الشهري",
    "results.solarPanels": "الألواح الشمسية",
    "results.requiredCapacity": "الاستطاعة المطلوبة",
    "results.numberOfPanels": "عدد الألواح",
    "results.panelArea": "المساحة المطلوبة",
    "results.batteryBank": "بنك البطاريات",
    "results.requiredStorage": "التخزين المطلوب",
    "results.usableStorage": "التخزين الفعّال",
    "results.batteryCapacity": "سعة البطارية",
    "results.totalBatteries": "إجمالي البطاريات",
    "results.series": "توصيل توالي",
    "results.parallel": "توصيل توازي",
    "results.actualTotal": "الإجمالي الفعلي",
    "results.storedEnergy": "الطاقة المخزنة",
    "results.inverter": "العاكس",
    "results.inverterCapacity": "استطاعة العاكس",
    "results.recommended": "الموصى به",
    "results.controller": "منظم الشحن",
    "results.controllerCurrent": "تيار منظم الشحن",
    "results.recommendedController": "منظم الشحن الموصى",
    "results.controllerType": "النوع",
    "results.mpptString": "حساب سلسلة MPPT",
    "results.panelsPerString": "ألواح لكل سلسلة",
    "results.totalStrings": "إجمالي السلاسل",
    "results.stringsPerMPPT": "سلاسل لكل MPPT",
    "results.stringVoc": "جهد السلسلة Voc",
    "results.stringVmp": "جهد السلسلة Vmp",
    "results.stringPower": "قدرة السلسلة",
    "results.mpptRange": "نطاق MPPT",
    "results.cost": "التكلفة التقريبية",
    "results.panelsCost": "الألواح",
    "results.batteriesCost": "البطاريات",
    "results.inverterCost": "العاكس",
    "results.controllerCost": "منظم الشحن",
    "results.accessories": "الملحقات (15%)",
    "results.totalCost": "الإجمالي",
    // Actions
    "action.pdf": "تصدير PDF",
    "action.share": "مشاركة",
    "action.print": "طباعة",
    // Cables
    "cables.title": "حساب حجم الكابلات والحماية",
    "cables.dcSection": "قسم التيار المستمر DC",
    "cables.acSection": "قسم التيار المتردد AC",
    "cables.pvStringCable": "كابل سلسلة الألواح PV",
    "cables.pvMainCable": "كابل رئيسي PV (من صندوق التجميع للعاكس)",
    "cables.batteryCable": "كابل البطاريات",
    "cables.acOutputCable": "كابل مخرج العاكس AC",
    "cables.acMainCable": "كابل رئيسي AC",
    "cables.cableSize": "مقطع الكابل",
    "cables.current": "التيار",
    "cables.voltageDrop": "هبوط الجهد",
    "cables.voltageDropPercent": "نسبة الهبوط",
    "cables.length": "طول الكابل (متر)",
    "cables.recommendedSize": "المقطع الموصى",
    "cables.maxCurrent": "أقصى تيار",
    "cables.status": "الحالة",
    "cables.ok": "مقبول",
    "cables.high": "مرتفع - زد مقطع الكابل",
    "cables.circuitBreaker": "القاطع / الفيوز",
    "cables.breakerRating": "تصنيف القاطع",
    "cables.breakerType": "نوع القاطع",
    "cables.breakerForPV": "حماية سلسلة الألواح",
    "cables.breakerForBattery": "حماية البطاريات",
    "cables.breakerForAC": "حماية مخرج AC",
    "cables.breakerForMainAC": "قاطع رئيسي AC",
    "cables.grounding": "التأريض",
    "cables.groundingRod": "قضيب تأريض",
    "cables.groundingConductor": "موصل التأريض",
    "cables.groundingResistance": "مقاومة التأريض",
    // Economics
    "econ.title": "التحليل الاقتصادي",
    "econ.paybackPeriod": "فترة الاسترداد",
    "econ.annualProduction": "الإنتاج السنوي المتوقع",
    "econ.monthlyProduction": "الإنتاج الشهري",
    "econ.costPerKWh": "تكلفة الكيلوواط·س",
    "econ.annualSavings": "التوفير السنوي",
    "econ.dieselComparison": "مقارنة مع المولد الديزل",
    "econ.gridComparison": "مقارنة مع الشبكة العامة",
    "econ.lcoe": "تكلفة الطوية (LCOE)",
    "econ.totalInvestment": "إجمالي الاستثمار",
    "econ.years": "سنوات",
    "econ.months": "شهر",
    "econ.kwhPerYear": "كيلوواط·س/سنة",
    "econ.usdPerKWh": "$/كيلوواط·س",
    "econ.usdPerYear": "$/سنة",
    "econ.dieselCost": "تكلفة الديزل",
    "econ.dieselSavings": "التوفير مقارنة بالديزل",
    "econ.co2Saved": "انبعاثات CO2 المتجنب",
    "econ.gridCost": "تكلفة الشبكة",
    "econ.gridSavings": "التوفير مقارنة بالشبكة",
    "econ.financing": "حاسبة التمويل",
    "econ.loanAmount": "مبلغ القرض",
    "econ.interestRate": "نسبة الفائدة (%)",
    "econ.loanTerm": "مدة القرض (سنوات)",
    "econ.monthlyPayment": "القسط الشهري",
    "econ.totalInterest": "إجمالي الفوائد",
    // BOM
    "bom.title": "قائمة المواد والكميات (BOM)",
    "bom.item": "البند",
    "bom.description": "الوصف",
    "bom.quantity": "الكمية",
    "bom.unit": "الوحدة",
    "bom.unitPrice": "سعر الوحدة",
    "bom.totalPrice": "السعر الإجمالي",
    "bom.notes": "ملاحظات",
    // Save
    "save.title": "إدارة المشاريع",
    "save.saveCurrent": "حفظ المشروع الحالي",
    "save.savedProjects": "المشاريع المحفوظة",
    "save.noProjects": "لا توجد مشاريع محفوظة",
    "save.load": "تحميل",
    "save.delete": "حذف",
    "save.export": "تصدير",
    "save.import": "استيراد",
    // Dark mode
    "dark.toggle": "الوضع الداكن",
    "light.toggle": "الوضع الفاتح",
    // Language
    "lang.ar": "العربية",
    "lang.en": "English",
    // Units
    "unit.watt": "واط",
    "unit.kwh": "كيلوواط·س",
    "unit.amp": "أمبير",
    "unit.volt": "فولت",
    "unit.mm2": "مم²",
    "unit.meter": "متر",
    "unit.usd": "$",
    "unit.degrees": "درجة",
    "unit.percent": "%",
    "unit.year": "سنة",
    "unit.month": "شهر",
    "unit.day": "يوم",
    "unit.hours": "ساعة",
  },
  en: {
    // Header
    "app.title": "Solar System Calculator",
    "app.subtitle": "Calculate your solar system components accurately and professionally",
    "badge.accurate": "Accurate Calc",
    "badge.instant": "Instant Results",
    // Tabs
    "tab.calculator": "Calculator",
    "tab.cables": "Cables & Protection",
    "tab.economics": "Economic Analysis",
    "tab.bom": "Bill of Materials",
    "tab.save": "Save Projects",
    // Project Info
    "project.title": "Project Information",
    "project.desc": "Enter project information to include in the report",
    "project.name": "Project Name",
    "project.client": "Client Name",
    "project.location": "Location",
    "project.date": "Date",
    "project.engineer": "Engineer Name",
    "project.number": "Project Number",
    "project.notes": "Notes",
    "project.show": "Show",
    "project.hide": "Hide",
    // Location & Solar
    "location.title": "Location & Solar Radiation",
    "location.governorate": "Governorate",
    "location.select": "Select Governorate",
    "location.annualAvg": "Annual Average Radiation",
    "location.peakSunHours": "Peak Sun Hours",
    "location.tiltAngle": "Optimal Tilt Angle",
    "location.latitude": "Latitude",
    "location.autoFill": "Auto-fill sunshine hours",
    // Load
    "load.title": "Electrical Load Table",
    "load.type": "Load Type",
    "load.residential": "Residential",
    "load.industrial": "Industrial",
    "load.name": "Device Name",
    "load.quantity": "Qty",
    "load.power": "Power (W)",
    "load.hours": "Hours/Day",
    "load.total": "Total (Wh)",
    "load.add": "Add Load",
    "load.peakLoad": "Peak Load",
    "load.dailyEnergy": "Daily Energy",
    // System Params
    "params.title": "System Parameters",
    "params.sunshine": "Sunshine Hours",
    "params.voltage": "System Voltage (V)",
    "params.backup": "Backup Days",
    "params.panelWattage": "Panel Wattage (W)",
    "params.systemType": "System Type",
    "params.onGrid": "Grid-Tied (On-Grid)",
    "params.offGrid": "Off-Grid",
    "params.hybrid": "Hybrid",
    "params.batteryType": "Battery Type",
    "params.leadAcid": "Lead-Acid",
    "params.lithium": "Lithium (LiFePO4)",
    "params.batteryCapacity": "Battery Capacity (Ah)",
    "params.batteryVoltage": "Battery Voltage (V)",
    "params.dod": "Depth of Discharge (DoD %)",
    "params.efficiency": "System Efficiency (%)",
    "params.inverterEfficiency": "Inverter Efficiency (%)",
    // Panel Specs
    "panel.title": "Solar Panel Specifications",
    "panel.voc": "Open Circuit Voltage Voc (V)",
    "panel.isc": "Short Circuit Current Isc (A)",
    "panel.vmp": "Max Power Voltage Vmp (V)",
    "panel.imp": "Max Power Current Imp (A)",
    // Calculate
    "calc.button": "Calculate System",
    // Results
    "results.title": "Calculation Results",
    "results.loadSummary": "Load Summary",
    "results.peakLoad": "Peak Load",
    "results.dailyConsumption": "Daily Consumption",
    "results.monthlyConsumption": "Monthly Consumption",
    "results.solarPanels": "Solar Panels",
    "results.requiredCapacity": "Required Capacity",
    "results.numberOfPanels": "Number of Panels",
    "results.panelArea": "Required Area",
    "results.batteryBank": "Battery Bank",
    "results.requiredStorage": "Required Storage",
    "results.usableStorage": "Usable Storage",
    "results.batteryCapacity": "Battery Capacity",
    "results.totalBatteries": "Total Batteries",
    "results.series": "Series Connection",
    "results.parallel": "Parallel Connection",
    "results.actualTotal": "Actual Total",
    "results.storedEnergy": "Stored Energy",
    "results.inverter": "Inverter",
    "results.inverterCapacity": "Inverter Capacity",
    "results.recommended": "Recommended",
    "results.controller": "Charge Controller",
    "results.controllerCurrent": "Controller Current",
    "results.recommendedController": "Recommended Controller",
    "results.controllerType": "Type",
    "results.mpptString": "MPPT String Calculation",
    "results.panelsPerString": "Panels Per String",
    "results.totalStrings": "Total Strings",
    "results.stringsPerMPPT": "Strings Per MPPT",
    "results.stringVoc": "String Voltage Voc",
    "results.stringVmp": "String Voltage Vmp",
    "results.stringPower": "String Power",
    "results.mpptRange": "MPPT Range",
    "results.cost": "Cost Estimate",
    "results.panelsCost": "Panels",
    "results.batteriesCost": "Batteries",
    "results.inverterCost": "Inverter",
    "results.controllerCost": "Controller",
    "results.accessories": "Accessories (15%)",
    "results.totalCost": "Total",
    // Actions
    "action.pdf": "Export PDF",
    "action.share": "Share",
    "action.print": "Print",
    // Cables
    "cables.title": "Cable Sizing & Protection",
    "cables.dcSection": "DC Section",
    "cables.acSection": "AC Section",
    "cables.pvStringCable": "PV String Cable",
    "cables.pvMainCable": "PV Main Cable (Combiner to Inverter)",
    "cables.batteryCable": "Battery Cable",
    "cables.acOutputCable": "Inverter AC Output Cable",
    "cables.acMainCable": "AC Main Cable",
    "cables.cableSize": "Cable Size",
    "cables.current": "Current",
    "cables.voltageDrop": "Voltage Drop",
    "cables.voltageDropPercent": "Drop Percentage",
    "cables.length": "Cable Length (m)",
    "cables.recommendedSize": "Recommended Size",
    "cables.maxCurrent": "Max Current",
    "cables.status": "Status",
    "cables.ok": "Acceptable",
    "cables.high": "High - Increase cable size",
    "cables.circuitBreaker": "Circuit Breaker / Fuse",
    "cables.breakerRating": "Breaker Rating",
    "cables.breakerType": "Breaker Type",
    "cables.breakerForPV": "PV String Protection",
    "cables.breakerForBattery": "Battery Protection",
    "cables.breakerForAC": "AC Output Protection",
    "cables.breakerForMainAC": "AC Main Breaker",
    "cables.grounding": "Grounding",
    "cables.groundingRod": "Grounding Rod",
    "cables.groundingConductor": "Grounding Conductor",
    "cables.groundingResistance": "Grounding Resistance",
    // Economics
    "econ.title": "Economic Analysis",
    "econ.paybackPeriod": "Payback Period",
    "econ.annualProduction": "Expected Annual Production",
    "econ.monthlyProduction": "Monthly Production",
    "econ.costPerKWh": "Cost per kWh",
    "econ.annualSavings": "Annual Savings",
    "econ.dieselComparison": "Diesel Generator Comparison",
    "econ.gridComparison": "Grid Electricity Comparison",
    "econ.lcoe": "Levelized Cost (LCOE)",
    "econ.totalInvestment": "Total Investment",
    "econ.years": "years",
    "econ.months": "months",
    "econ.kwhPerYear": "kWh/year",
    "econ.usdPerKWh": "$/kWh",
    "econ.usdPerYear": "$/year",
    "econ.dieselCost": "Diesel Cost",
    "econ.dieselSavings": "Savings vs Diesel",
    "econ.co2Saved": "CO2 Emissions Avoided",
    "econ.gridCost": "Grid Cost",
    "econ.gridSavings": "Savings vs Grid",
    "econ.financing": "Financing Calculator",
    "econ.loanAmount": "Loan Amount",
    "econ.interestRate": "Interest Rate (%)",
    "econ.loanTerm": "Loan Term (years)",
    "econ.monthlyPayment": "Monthly Payment",
    "econ.totalInterest": "Total Interest",
    // BOM
    "bom.title": "Bill of Materials (BOM)",
    "bom.item": "Item",
    "bom.description": "Description",
    "bom.quantity": "Qty",
    "bom.unit": "Unit",
    "bom.unitPrice": "Unit Price",
    "bom.totalPrice": "Total Price",
    "bom.notes": "Notes",
    // Save
    "save.title": "Project Management",
    "save.saveCurrent": "Save Current Project",
    "save.savedProjects": "Saved Projects",
    "save.noProjects": "No saved projects",
    "save.load": "Load",
    "save.delete": "Delete",
    "save.export": "Export",
    "save.import": "Import",
    // Dark mode
    "dark.toggle": "Dark Mode",
    "light.toggle": "Light Mode",
    // Language
    "lang.ar": "العربية",
    "lang.en": "English",
    // Units
    "unit.watt": "W",
    "unit.kwh": "kWh",
    "unit.amp": "A",
    "unit.volt": "V",
    "unit.mm2": "mm²",
    "unit.meter": "m",
    "unit.usd": "$",
    "unit.degrees": "°",
    "unit.percent": "%",
    "unit.year": "year",
    "unit.month": "month",
    "unit.day": "day",
    "unit.hours": "h",
  }
};
